{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ephpm.fullname" . }}-env
  labels:
    {{- include "ephpm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.cluster.enabled .Values.cluster.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ephpm.fullname" . }}-cluster
  labels:
    {{- include "ephpm.labels" . | nindent 4 }}
type: Opaque
stringData:
  gossip-secret: {{ .Values.cluster.secret | quote }}
{{- end }}
