{{- if and .Values.cluster.enabled .Values.cluster.secret (not .Values.cluster.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ephpm.fullname" . }}-cluster
  labels:
    {{- include "ephpm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.cluster.secretKey }}: {{ .Values.cluster.secret | quote }}
{{- end }}
