{{- if include "ephpm.isStatefulSet" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ephpm.fullname" . }}
  labels:
    {{- include "ephpm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ephpm.headlessServiceName" . }}
  replicas: {{ include "ephpm.replicas" . }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "ephpm.selectorLabels" . | nindent 6 }}
  template:
    {{- include "ephpm.podTemplateSpec" . | nindent 4 }}
  {{- if .Values.db.sqlite.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with .Values.db.sqlite.persistence.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.db.sqlite.persistence.size }}
  {{- end }}
{{- end }}
