//! Clustered Turso CDC replication e2e (`[db.sqlite]` + `[cluster]`).
//!
//! A **self-managed** suite (`SELF_MANAGED_SUITES` in `xtask/src/e2e_bare.rs`):
//! the harness starts no node for it. It spawns its own ephpm processes on
//! 127.0.0.1 because the scenarios need process-lifecycle control the shared
//! fixtures cannot offer — killing the elected primary, and starting a cold
//! node after the primary already has data. Every port is drawn fresh from the
//! kernel, so nothing here can collide with the harness's fixed-port nodes.
//!
//! The lifecycle coverage:
//!
//! - **Election + replication + promotion**
//!   ([`auto_election_replicates_and_survives_losing_the_primary`]) — three
//!   `role = "auto"` nodes elect exactly one primary (gossip KV election,
//!   `ephpm-cluster/src/sqlite_election.rs`), its writes reach both replicas
//!   over the CDC ship/apply path (`ephpm-server/src/turso_cdc.rs`), and
//!   killing it promotes a survivor without losing already-replicated rows.
//! - **Cold-replica snapshot bootstrap**
//!   ([`a_cold_replica_bootstraps_from_the_primary_snapshot`]) — an empty node
//!   joins a primary that already holds data and catches up via the logical
//!   dump, then stays current off the post-snapshot tail.
//!
//! Two further tests pin defects that were **found by writing this suite**
//! and have since been fixed — each keeps the original observed log
//! evidence and root cause in its doc comment, plus the fix mechanism:
//!
//! - [`a_joining_node_must_not_steal_an_established_primary`] — issue #314,
//!   fixed by the election's startup grace + deterministic conflict
//!   resolution (`ephpm-cluster/src/sqlite_election.rs`).
//! - [`post_failover_writes_replicate_to_the_survivor`] — issue #315,
//!   fixed by scoping replication watermarks to a per-database CDC log
//!   identity (`Frame::Hello` / `resolve_subscribe_watermark` in
//!   `ephpm-server/src/turso_cdc.rs`).
//!
//! They started life as `#[ignore]`d executable specifications; dropping
//! the attribute was the designed verification step for the fixes.
//!
//! The SQL surface is litewire's Hrana HTTP API (`hrana_listen`), because it
//! needs nothing beyond reqwest + JSON — no MySQL client, no PHP. The
//! clustered CDC path serves Hrana from the same wire factory as the MySQL
//! frontend, so what this suite observes is the replicated database.
//!
//! Environment:
//! - `EPHPM_BINARY` — path to an ephpm binary. Unset ⇒ the suite self-skips
//!   (so a bare `cargo test` still compiles and passes without a build).
//!
//! Skipped on Windows: clustered mode is Linux/macOS + experimental (see
//! CLAUDE.md, "Windows database").
//!
//! Deadlines are generous on purpose: the election heartbeats every 5s with a
//! 10s TTL, gossip failure detection adds its own delay, and CI runners are
//! slow. Every wait polls against a deadline — never sleep-and-hope.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

use anyhow::{Context, Result, anyhow, bail};
use ephpm_e2e::{PortKind, PortLease, PortReserver, ephpm_binary_env};
use serde_json::json;
use tempfile::TempDir;

/// Shared secret for the fixture cluster. Fixed is fine: throwaway loopback
/// processes, never production.
const CLUSTER_SECRET: &str = "turso-cdc-e2e-secret-not-for-production";

/// How often the pollers re-check a condition.
const POLL_INTERVAL: Duration = Duration::from_millis(500);

/// Per-node config. Mirrors the shape of the harness cluster template
/// (`xtask/src/e2e_bare.rs::CLUSTER_NODE_TEMPLATE`) but is deliberately a
/// **private copy**: this suite's topology needs (`hrana_listen`, deferred
/// spawn, kill) must never leak into the shared template (issues #288/#295).
const NODE_TEMPLATE: &str = r#"# Auto-generated by the turso_cdc e2e suite — do not edit.
[server]
listen = "127.0.0.1:{HTTP_PORT}"
document_root = "{DOCROOT}"
index_files = ["index.html"]

[server.request]
trusted_hosts = ["localhost", "127.0.0.1", "127.0.0.1:{HTTP_PORT}"]

[server.metrics]
enabled = true

[db.sqlite]
path = "{DATA_DIR}/cdc.db"

[db.sqlite.proxy]
mysql_listen = "127.0.0.1:{MYSQL_PORT}"
hrana_listen = "127.0.0.1:{HRANA_PORT}"

{REPLICATION_BLOCK}

[cluster]
enabled = true
bind = "127.0.0.1:{GOSSIP_PORT}"
join = [{CLUSTER_JOIN}]
node_id = "{NODE_ID}"
cluster_id = "ephpm-e2e-turso-cdc"
secret = "{SECRET}"

[cluster.channel]
listen = "127.0.0.1:{CHANNEL_PORT}"

[cluster.kv]
data_port = {KV_DATA_PORT}
"#;

struct NodePorts {
    http: u16,
    mysql: u16,
    hrana: u16,
    gossip: u16,
    /// Cluster-channel (CDC transport) listen port. Reserved as its own
    /// OS-assigned ephemeral port and pinned via `[cluster.channel] listen`
    /// rather than derived as `gossip + 2` — a derived port is not reserved
    /// from the kernel and collided under parallelism (issue #383).
    channel: u16,
    kv_data: u16,
    /// Probe sockets holding this node's six ports until it is spawned.
    ///
    /// `None` once the node has been spawned (or, defensively, if a caller ever
    /// spawns twice). Holding is what makes reserving ports for a node that
    /// starts ~100s later safe — see [`ephpm_e2e::PortLease`] and issue #438.
    lease: Option<PortLease>,
}

/// How a node's `[db.sqlite.replication]` block is written.
///
/// `Auto` is the production-shaped path (gossip election decides). The
/// explicit variants exist so a test can pin the topology and exercise one
/// mechanism — the snapshot bootstrap — without the election as a variable;
/// `determine_role` in `turso_cdc.rs` honours all three.
#[derive(Debug, Clone, Copy)]
enum RoleSpec {
    Auto,
    Primary,
    /// Replica of the node at this index. The address a replica dials is the
    /// primary's **cluster channel** (`channel_addr`), not its gossip port.
    ReplicaOf(usize),
}

struct CdcCluster {
    binary: PathBuf,
    docroot: PathBuf,
    ports: Vec<NodePorts>,
    /// `Some(child)` while the node runs; `None` before spawn and after kill.
    children: Vec<Option<Child>>,
    tempdir: TempDir,
}

impl CdcCluster {
    /// Reserve port sets for `total` nodes (spawning none yet) and prepare
    /// the scratch layout. Ports for *every* node — including ones spawned
    /// later — are reserved up front so each node's `join` list can name the
    /// full eventual membership.
    ///
    /// Reserved here means **held**: each node keeps its probe sockets open
    /// until [`Self::spawn`] releases them a few instructions before
    /// `Command::spawn`. This suite is the reason that matters —
    /// [`a_joining_node_must_not_steal_an_established_primary`] does not start
    /// node 3 until ~100s after `prepare`, and for all of that time a live
    /// 3-node cluster is churning gossip, CDC and MySQL connections through the
    /// ephemeral range. With the old bind-read-close reservation the kernel
    /// re-issued node 3's port to one of those connections roughly 1 run in 25,
    /// and the node died on `Address already in use` — surfacing as "node 3
    /// never became healthy within 90s", which reads like a cluster regression
    /// and burns a whole e2e leg (issue #438).
    async fn prepare(binary: &Path, total: usize) -> Result<Self> {
        let tempdir =
            tempfile::Builder::new().prefix("ephpm-e2e-cdc-").tempdir().context("tempdir")?;
        let docroot = tempdir.path().join("docroot");
        fs::create_dir_all(&docroot).context("create docroot")?;
        fs::write(docroot.join("index.html"), "cdc-e2e").context("write index.html")?;

        // Gossip is UDP; the channel port is pinned explicitly here (not
        // derived as `gossip + 2`), so it is reserved as an ordinary TCP port.
        let mut reserver = PortReserver::new();
        let mut ports = Vec::with_capacity(total);
        for _ in 0..total {
            let lease = reserver
                .lease(&[
                    PortKind::Tcp, // http
                    PortKind::Tcp, // mysql
                    PortKind::Tcp, // hrana
                    PortKind::Udp, // gossip
                    PortKind::Tcp, // cluster channel
                    PortKind::Tcp, // kv data plane
                ])
                .await?;
            ports.push(NodePorts {
                http: lease.port(0),
                mysql: lease.port(1),
                hrana: lease.port(2),
                gossip: lease.port(3),
                channel: lease.port(4),
                kv_data: lease.port(5),
                lease: Some(lease),
            });
        }

        let mut children = Vec::with_capacity(total);
        children.resize_with(total, || None);
        Ok(Self { binary: binary.to_path_buf(), docroot, ports, children, tempdir })
    }

    /// The cluster-channel address peers dial to reach node `i` — the
    /// explicit `[cluster.channel] listen` port, not a `gossip + 2` derivation.
    fn channel_addr(&self, i: usize) -> String {
        format!("127.0.0.1:{}", self.ports[i].channel)
    }

    /// Spawn node `i` with the given replication role and wait for it to
    /// report healthy.
    async fn spawn(&mut self, i: usize, role: RoleSpec) -> Result<()> {
        assert!(self.children[i].is_none(), "node {i} already running");

        let replication_block = match role {
            RoleSpec::Auto => "[db.sqlite.replication]\nrole = \"auto\"".to_string(),
            RoleSpec::Primary => "[db.sqlite.replication]\nrole = \"primary\"".to_string(),
            RoleSpec::ReplicaOf(p) => format!(
                "[db.sqlite.replication]\nrole = \"replica\"\nprimary_grpc_url = \"{}\"",
                self.channel_addr(p)
            ),
        };

        let node_dir = self.tempdir.path().join(format!("node-{i}"));
        let data_dir = node_dir.join("data");
        fs::create_dir_all(&data_dir).context("create data dir")?;

        let join = self
            .ports
            .iter()
            .enumerate()
            .filter(|(j, _)| *j != i)
            .map(|(_, p)| format!("\"127.0.0.1:{}\"", p.gossip))
            .collect::<Vec<_>>()
            .join(", ");

        let p = &self.ports[i];
        let config = NODE_TEMPLATE
            .replace("{HTTP_PORT}", &p.http.to_string())
            .replace("{MYSQL_PORT}", &p.mysql.to_string())
            .replace("{HRANA_PORT}", &p.hrana.to_string())
            .replace("{GOSSIP_PORT}", &p.gossip.to_string())
            .replace("{CHANNEL_PORT}", &p.channel.to_string())
            .replace("{KV_DATA_PORT}", &p.kv_data.to_string())
            .replace("{NODE_ID}", &format!("cdc-node-{i}"))
            .replace("{CLUSTER_JOIN}", &join)
            .replace("{REPLICATION_BLOCK}", &replication_block)
            .replace("{SECRET}", CLUSTER_SECRET)
            .replace("{DATA_DIR}", &escape_toml(&data_dir))
            .replace("{DOCROOT}", &escape_toml(&self.docroot));

        let config_path = node_dir.join("ephpm.toml");
        fs::write(&config_path, config).context("write config")?;
        let stdout = fs::File::create(node_dir.join("stdout.log")).context("stdout log")?;
        let stderr = fs::File::create(node_dir.join("stderr.log")).context("stderr log")?;

        let http_port = self.ports[i].http;
        eprintln!("[cdc-e2e] spawning node {i} (http 127.0.0.1:{http_port})");
        // Hand the ports off: release this node's probes and spawn in the same
        // breath, so nothing else can be issued one in between (issue #438).
        if let Some(lease) = self.ports[i].lease.take() {
            lease.release();
        }
        let child = Command::new(&self.binary)
            .args(["serve", "--config"])
            .arg(&config_path)
            .stdout(Stdio::from(stdout))
            .stderr(Stdio::from(stderr))
            .spawn()
            .with_context(|| format!("spawn node {i} ({})", self.binary.display()))?;
        self.children[i] = Some(child);

        // Generous: a cold replica fetches and applies the primary's snapshot
        // *before* its listeners come up, so on that path health is gated
        // behind the whole bootstrap.
        self.wait_healthy(i, Duration::from_secs(90)).await
    }

    /// Kill node `i` hard (SIGKILL / TerminateProcess) — this is the crash
    /// the failover phase is about, so no graceful shutdown.
    fn kill(&mut self, i: usize) {
        if let Some(mut child) = self.children[i].take() {
            eprintln!("[cdc-e2e] killing node {i}");
            let _ = child.kill();
            let _ = child.wait();
        }
    }

    async fn wait_healthy(&self, i: usize, timeout: Duration) -> Result<()> {
        let url = format!("http://127.0.0.1:{}/_ephpm/health", self.ports[i].http);
        let deadline = Instant::now() + timeout;
        let client = reqwest::Client::new();
        let mut last = String::from("no attempt");
        while Instant::now() < deadline {
            match client.get(&url).timeout(Duration::from_secs(2)).send().await {
                Ok(resp) if resp.status().as_u16() == 200 => return Ok(()),
                Ok(resp) => last = format!("HTTP {}", resp.status()),
                Err(e) => last = e.to_string(),
            }
            tokio::time::sleep(POLL_INTERVAL).await;
        }
        Err(anyhow!("node {i} never became healthy within {timeout:?}: {last}"))
    }

    /// Read one unlabeled metric from node `i`'s Prometheus endpoint.
    ///
    /// `None` when the node is unreachable or the series is absent — callers
    /// poll, so "not yet" and "not exposed" are the same answer.
    async fn metric(&self, i: usize, name: &str) -> Option<f64> {
        let url = format!("http://127.0.0.1:{}/metrics", self.ports[i].http);
        let client = reqwest::Client::new();
        let resp = client.get(&url).timeout(Duration::from_secs(2)).send().await.ok()?;
        let text = resp.text().await.ok()?;
        parse_metric(&text, name)
    }

    /// Poll until exactly one of `alive` reports
    /// `ephpm_cdc_subscribers == alive.len() - 1` while every other alive
    /// node reports 0. Returns the primary's node index.
    ///
    /// That condition is the whole phase-1 assertion in one shape: a sole
    /// primary exists, *and* every replica has attached to it (subscribers is
    /// the count of live replication streams, so this cannot pass on a
    /// half-formed cluster).
    async fn wait_for_sole_primary(&self, alive: &[usize], timeout: Duration) -> usize {
        let expected = to_f64(alive.len() - 1);
        let deadline = Instant::now() + timeout;
        loop {
            let mut subs = Vec::with_capacity(alive.len());
            for &i in alive {
                subs.push((i, self.metric(i, "ephpm_cdc_subscribers").await));
            }

            let full: Vec<usize> =
                subs.iter().filter(|(_, s)| *s == Some(expected)).map(|(i, _)| *i).collect();
            let rest_zero =
                subs.iter().filter(|(i, _)| !full.contains(i)).all(|(_, s)| *s == Some(0.0));
            if full.len() == 1 && rest_zero {
                eprintln!("[cdc-e2e] sole primary: node {} (subscribers {subs:?})", full[0]);
                return full[0];
            }

            assert!(
                Instant::now() < deadline,
                "no sole primary with {expected} attached replicas emerged within {timeout:?}; \
                 last ephpm_cdc_subscribers: {subs:?}"
            );
            tokio::time::sleep(POLL_INTERVAL).await;
        }
    }

    /// Execute one statement over node `i`'s Hrana HTTP endpoint.
    ///
    /// The route is `/v2/pipeline` — litewire's `litewire-hrana` serves the
    /// Hrana 3 protocol under the sqld-compatible **v2** path, and there is no
    /// `/v3/pipeline`. (`tests/hrana.rs` posts to `/v3/pipeline`, but only
    /// when `EPHPM_HRANA_URL` is set, which the bare harness never sets — so
    /// that assertion has never actually executed.)
    async fn sql(&self, i: usize, sql: &str) -> Result<serde_json::Value> {
        let url = format!("http://127.0.0.1:{}/v2/pipeline", self.ports[i].hrana);
        let body = json!({
            "baton": null,
            "requests": [
                { "type": "execute", "stmt": { "sql": sql, "args": [] } },
                { "type": "close" }
            ]
        });
        let resp = reqwest::Client::new()
            .post(&url)
            .json(&body)
            .timeout(Duration::from_secs(10))
            .send()
            .await
            .with_context(|| format!("POST {url}"))?;
        if !resp.status().is_success() {
            bail!("hrana on node {i} returned HTTP {}", resp.status());
        }
        let v: serde_json::Value = resp.json().await.context("hrana response json")?;
        if let Some(results) = v["results"].as_array() {
            for r in results {
                if r["type"] == "error" {
                    bail!(
                        "hrana statement error on node {i}: {}",
                        r["error"]["message"].as_str().unwrap_or("unknown")
                    );
                }
            }
        }
        Ok(v)
    }

    /// Execute a statement that must succeed (panics with context otherwise).
    async fn sql_ok(&self, i: usize, sql: &str) {
        self.sql(i, sql).await.unwrap_or_else(|e| panic!("SQL on node {i} failed: {e:#}\n  {sql}"));
    }

    /// Poll node `i` until `sql`'s first result column equals `want`.
    async fn wait_for_rows(
        &self,
        i: usize,
        sql: &str,
        want: &[&str],
        timeout: Duration,
        what: &str,
    ) {
        let deadline = Instant::now() + timeout;
        loop {
            let last = match self.sql(i, sql).await {
                Ok(v) => {
                    let got = first_column(&v);
                    if got == want {
                        eprintln!("[cdc-e2e] node {i}: {what} — converged ({got:?})");
                        return;
                    }
                    format!("rows {got:?}")
                }
                Err(e) => format!("error: {e:#}"),
            };
            assert!(
                Instant::now() < deadline,
                "{what}: node {i} never converged to {want:?} within {timeout:?}; last: {last}"
            );
            tokio::time::sleep(POLL_INTERVAL).await;
        }
    }
}

impl Drop for CdcCluster {
    fn drop(&mut self) {
        let dump = std::thread::panicking();
        for i in 0..self.children.len() {
            self.kill(i);
        }
        if dump {
            // Both streams: ephpm's `tracing` output goes to stdout, and only
            // hard startup failures land on stderr — dumping stderr alone
            // yields four empty blocks and tells you nothing.
            for i in 0..self.children.len() {
                let node_dir = self.tempdir.path().join(format!("node-{i}"));
                for stream in ["stderr", "stdout"] {
                    let Ok(contents) = fs::read_to_string(node_dir.join(format!("{stream}.log")))
                    else {
                        continue;
                    };
                    let lines: Vec<&str> = contents.lines().collect();
                    if lines.is_empty() {
                        continue;
                    }
                    eprintln!("--- [cdc-e2e] node {i} {stream} (last 60 lines) ---");
                    for line in &lines[lines.len().saturating_sub(60)..] {
                        eprintln!("{line}");
                    }
                    eprintln!("--- end node {i} {stream} ---");
                }
            }
        }
    }
}

// ── helpers ─────────────────────────────────────────────────────────────────

fn escape_toml(path: &Path) -> String {
    let mut out = String::new();
    for ch in path.to_string_lossy().chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c if c.is_control() => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Value of the first unlabeled Prometheus series named exactly `name`.
fn parse_metric(text: &str, name: &str) -> Option<f64> {
    text.lines()
        .filter(|l| !l.starts_with('#'))
        .find(|l| l.split_whitespace().next() == Some(name))
        .and_then(|l| l.split_whitespace().last())
        .and_then(|v| v.parse().ok())
}

/// First column of the first statement's result rows, as strings.
fn first_column(v: &serde_json::Value) -> Vec<String> {
    let Some(rows) = v["results"][0]["response"]["result"]["rows"].as_array() else {
        return Vec::new();
    };
    rows.iter()
        .map(|row| {
            let cell = &row[0];
            cell["value"]
                .as_str()
                .map_or_else(|| cell["value"].to_string(), std::string::ToString::to_string)
        })
        .collect()
}

#[allow(clippy::cast_precision_loss)]
fn to_f64(n: usize) -> f64 {
    n as f64
}

// ── the test ────────────────────────────────────────────────────────────────

/// Guard shared by every test here: clustered mode is Linux/macOS, and the
/// suite needs a real binary to spawn. Returns `None` when the test should
/// skip.
fn binary_or_skip() -> Option<PathBuf> {
    if cfg!(windows) {
        eprintln!("clustered Turso CDC is not validated on Windows — skipping");
        return None;
    }
    let bin = ephpm_binary_env();
    if bin.is_none() {
        eprintln!("EPHPM_BINARY not set — skipping (needs a built ephpm binary)");
    }
    bin
}

/// The production-shaped path: three `role = "auto"` nodes elect a single
/// primary, its writes reach both replicas, and killing it promotes a
/// survivor without losing what was already replicated.
///
/// One test rather than three because the phases genuinely depend on each
/// other — you cannot assert a failover without first having an established
/// primary and an attached replica — and one 3-process topology is cheaper
/// than three.
#[tokio::test(flavor = "multi_thread")]
async fn auto_election_replicates_and_survives_losing_the_primary() {
    let Some(binary) = binary_or_skip() else { return };

    let mut cluster = CdcCluster::prepare(&binary, 3).await.expect("prepare fixture");
    for i in 0..3 {
        cluster.spawn(i, RoleSpec::Auto).await.unwrap_or_else(|e| panic!("start node {i}: {e:#}"));
    }

    // ── Exactly one primary, with both replicas actually attached ───────
    let primary = cluster.wait_for_sole_primary(&[0, 1, 2], Duration::from_secs(90)).await;

    // ── Writes on the primary reach both replicas ───────────────────────
    cluster.sql_ok(primary, "CREATE TABLE cdc_e2e (id INTEGER PRIMARY KEY, v TEXT)").await;
    cluster.sql_ok(primary, "INSERT INTO cdc_e2e (id, v) VALUES (1, 'alpha'), (2, 'beta')").await;
    for r in (0..3).filter(|&i| i != primary) {
        cluster
            .wait_for_rows(
                r,
                "SELECT v FROM cdc_e2e ORDER BY id",
                &["alpha", "beta"],
                Duration::from_secs(60),
                "primary write replicates",
            )
            .await;
    }

    // ── Kill the primary: a survivor is promoted, and the data survives ──
    cluster.kill(primary);
    let survivors: Vec<usize> = (0..3).filter(|&i| i != primary).collect();
    let new_primary = cluster.wait_for_sole_primary(&survivors, Duration::from_secs(120)).await;
    assert_ne!(new_primary, primary, "the dead primary cannot win the re-election");

    // Every survivor still serves what it had replicated before the failover.
    // (Whether *new* writes replicate afterwards is covered separately by
    // `post_failover_writes_replicate_to_the_survivor`.)
    for s in survivors {
        cluster
            .wait_for_rows(
                s,
                "SELECT v FROM cdc_e2e ORDER BY id",
                &["alpha", "beta"],
                Duration::from_secs(30),
                "pre-failover data survives the failover",
            )
            .await;
    }
}

/// After a failover, writes accepted by the newly promoted primary must reach
/// the surviving replica.
///
/// **Pins issue #315** (fixed; this test began life `#[ignore]`d as the
/// executable spec of the defect).
///
/// The defect: `turso_cdc`'s `change_id` is a **per-node** sequence — every
/// node's local `turso_cdc` log numbers from 1 — but the replication
/// protocol treated the watermark as if it were cluster-global.
/// `Frame::Subscribe` carried the replica's `applied_change_id` and the
/// primary opened `CdcTailer::new(mgmt, from)` at exactly that number *in
/// its own log*. Across a promotion those two numbers describe different
/// sequences.
///
/// Observed, with `cdc-node-2` the original primary and `cdc-node-0` promoted
/// after it was killed:
///
/// ```text
/// cdc-node-1  CDC replica: subscribed  from_change_id=5   (watermark from node-2)
/// cdc-node-0  CDC: subscriber attached from_change_id=5   (tailer over node-0's log)
/// ```
///
/// Node 0 had been a replica, and `apply_batch` writes go through the mgmt
/// connection with capture off, so its own log was empty. The post-failover
/// `INSERT` it accepted was captured at `change_id` 1 or 2 — below the
/// subscriber's cursor of 5 — so the tailer never yielded it: silent,
/// unbounded write loss after any failover.
///
/// The fix scopes every watermark to a persistent per-database *log
/// identity*: the primary announces its log id as the first frame of every
/// stream (`Frame::Hello`), and the replica keeps its cursor per log id —
/// on a source switch it re-seeds litewire's watermark table so the
/// promoted node's writes cannot land below the cursor. See the module
/// docs in `ephpm-server/src/turso_cdc.rs`.
#[tokio::test(flavor = "multi_thread")]
async fn post_failover_writes_replicate_to_the_survivor() {
    let Some(binary) = binary_or_skip() else { return };

    let mut cluster = CdcCluster::prepare(&binary, 3).await.expect("prepare fixture");
    for i in 0..3 {
        cluster.spawn(i, RoleSpec::Auto).await.unwrap_or_else(|e| panic!("start node {i}: {e:#}"));
    }
    let primary = cluster.wait_for_sole_primary(&[0, 1, 2], Duration::from_secs(90)).await;

    cluster.sql_ok(primary, "CREATE TABLE failover_e2e (id INTEGER PRIMARY KEY, v TEXT)").await;
    cluster.sql_ok(primary, "INSERT INTO failover_e2e (id, v) VALUES (1, 'alpha')").await;
    for r in (0..3).filter(|&i| i != primary) {
        cluster
            .wait_for_rows(
                r,
                "SELECT v FROM failover_e2e ORDER BY id",
                &["alpha"],
                Duration::from_secs(60),
                "pre-failover write replicates",
            )
            .await;
    }

    cluster.kill(primary);
    let survivors: Vec<usize> = (0..3).filter(|&i| i != primary).collect();
    let new_primary = cluster.wait_for_sole_primary(&survivors, Duration::from_secs(120)).await;

    cluster.sql_ok(new_primary, "INSERT INTO failover_e2e (id, v) VALUES (2, 'beta')").await;
    for s in survivors.into_iter().filter(|&s| s != new_primary) {
        cluster
            .wait_for_rows(
                s,
                "SELECT v FROM failover_e2e ORDER BY id",
                &["alpha", "beta"],
                Duration::from_secs(90),
                "post-failover write replicates to the survivor",
            )
            .await;
    }
}

/// Cold-replica bootstrap: a node with an **empty** database joins a primary
/// that already holds data and catches up via the logical-snapshot path
/// (`maybe_bootstrap_cold_replica` / `serve_snapshot` in `turso_cdc.rs`),
/// then stays current off the post-snapshot CDC tail.
///
/// Roles are pinned explicitly (`role = "primary"` / `"replica"`) rather than
/// elected, isolating the snapshot mechanism — which is what this test is
/// about — from election timing. (Historically this was forced: with
/// `role = "auto"`, a joining node used to take the primary role away from
/// the incumbent — issue #314, since fixed and pinned by
/// [`a_joining_node_must_not_steal_an_established_primary`].)
///
/// The two writes straddle the join on purpose: `alpha`/`beta` exist before
/// the replica is ever started, so only the snapshot can deliver them, while
/// `gamma` lands afterwards and can only arrive by the tail. Together they
/// prove the handoff between the two has neither a gap nor a duplicate.
#[tokio::test(flavor = "multi_thread")]
async fn a_cold_replica_bootstraps_from_the_primary_snapshot() {
    let Some(binary) = binary_or_skip() else { return };

    let mut cluster = CdcCluster::prepare(&binary, 2).await.expect("prepare fixture");
    cluster.spawn(0, RoleSpec::Primary).await.expect("start primary");

    // Data exists BEFORE the replica is ever started, so a tail-from-zero
    // cannot account for it — only a snapshot can.
    cluster.sql_ok(0, "CREATE TABLE cold_e2e (id INTEGER PRIMARY KEY, v TEXT)").await;
    cluster.sql_ok(0, "INSERT INTO cold_e2e (id, v) VALUES (1, 'alpha'), (2, 'beta')").await;

    cluster.spawn(1, RoleSpec::ReplicaOf(0)).await.expect("start cold replica");
    cluster
        .wait_for_rows(
            1,
            "SELECT v FROM cold_e2e ORDER BY id",
            &["alpha", "beta"],
            Duration::from_secs(120),
            "cold replica bootstraps pre-existing data",
        )
        .await;

    // Post-snapshot writes arrive by the tail, and nothing is double-applied.
    cluster.sql_ok(0, "INSERT INTO cold_e2e (id, v) VALUES (3, 'gamma')").await;
    cluster
        .wait_for_rows(
            1,
            "SELECT v FROM cold_e2e ORDER BY id",
            &["alpha", "beta", "gamma"],
            Duration::from_secs(60),
            "cold replica tails post-snapshot writes",
        )
        .await;
}

/// A node joining an established cluster must not become the primary.
///
/// **Pins issue #314** (fixed; this test began life `#[ignore]`d as the
/// executable spec of the defect).
///
/// Observed with a 3-node `role = "auto"` cluster plus a late joiner
/// (`cdc-node-3`, an empty database):
///
/// ```text
/// 21:41:58  cdc-node-2  elected as SQLite primary        (holds the data)
/// 21:42:04  cdc-node-3  elected as SQLite primary        (empty, just booted)
/// 21:42:08  cdc-node-2  role changed Primary -> Replica{ primary: node-3 }
/// ```
///
/// Two independent causes, both in `ephpm-cluster/src/sqlite_election.rs`:
///
/// 1. `determine_initial_role` ran before gossip had converged.
///    `should_be_primary` asks `cluster.nodes()`, which at that instant holds
///    only the local node, so "lowest-ordinal alive node" was trivially true
///    for *every* freshly started node. It then `publish_claim`ed,
///    overwriting the incumbent's claim in the gossip KV.
/// 2. `evaluate_role` only re-elected when there was no claim or the claimant
///    was dead. Faced with a live claim from another node it demoted
///    unconditionally — so the documented "lowest ordinal wins" rule was not
///    enforced against an incumbent, and the **last writer** won instead.
///    Here the *highest*-ordinal node took the role from `cdc-node-2`.
///
/// Impact of the defect: the cluster re-rooted onto an empty database. The
/// joiner believed it was primary, so it skipped
/// `maybe_bootstrap_cold_replica` and never fetched a snapshot; the nodes
/// that actually held the data demoted and re-subscribed from
/// `change_id = 0`.
///
/// The fix: a freshly started node may not publish a *first* primary claim
/// until a startup grace (> claim TTL + heartbeat) has elapsed, so a live
/// incumbent's claim always arrives first; and a live-claim conflict is
/// resolved deterministically (lowest node id) instead of last-writer-wins.
#[tokio::test(flavor = "multi_thread")]
async fn a_joining_node_must_not_steal_an_established_primary() {
    let Some(binary) = binary_or_skip() else { return };

    let mut cluster = CdcCluster::prepare(&binary, 4).await.expect("prepare fixture");
    for i in 0..3 {
        cluster.spawn(i, RoleSpec::Auto).await.unwrap_or_else(|e| panic!("start node {i}: {e:#}"));
    }
    let primary = cluster.wait_for_sole_primary(&[0, 1, 2], Duration::from_secs(90)).await;
    cluster.sql_ok(primary, "CREATE TABLE steal_e2e (id INTEGER PRIMARY KEY, v TEXT)").await;
    cluster.sql_ok(primary, "INSERT INTO steal_e2e (id, v) VALUES (1, 'alpha')").await;

    // A fourth node joins cold. The established primary must keep the role.
    cluster.spawn(3, RoleSpec::Auto).await.expect("start joining node");
    let after = cluster.wait_for_sole_primary(&[0, 1, 2, 3], Duration::from_secs(120)).await;
    assert_eq!(after, primary, "a joining node must not take the primary role");

    // And the joiner catches up as a replica, rather than re-rooting the
    // cluster onto its own empty database.
    cluster
        .wait_for_rows(
            3,
            "SELECT v FROM steal_e2e ORDER BY id",
            &["alpha"],
            Duration::from_secs(120),
            "the joining node bootstraps as a replica",
        )
        .await;
}
