//! Clustered Turso CDC replication e2e (`[db.sqlite]` + `[cluster]`).
//!
//! A **self-managed** suite (`SELF_MANAGED_SUITES` in `xtask/src/e2e_bare.rs`):
//! the harness starts no node for it. It spawns its own ephpm processes on
//! 127.0.0.1 because the scenarios need process-lifecycle control the shared
//! fixtures cannot offer — killing the elected primary, and starting a cold
//! node after the primary already has data. Every port is drawn fresh from the
//! kernel, so nothing here can collide with the harness's fixed-port nodes.
//!
//! What it proves, in order, on one cluster:
//!
//! 1. **Election** — with three nodes up, exactly one becomes primary (gossip
//!    KV election, `ephpm-cluster/src/sqlite_election.rs`), observed as the
//!    single node whose `ephpm_cdc_subscribers` gauge equals the number of
//!    replicas while every other node reports 0.
//! 2. **Replication** — writes on the primary become visible on both replicas
//!    (the CDC ship/apply path in `ephpm-server/src/turso_cdc.rs`).
//! 3. **Cold bootstrap** — a fourth node started *after* the primary has data
//!    catches up via the logical-snapshot path, then keeps up via the tail.
//! 4. **Failover** — the primary process is killed; a survivor is elected and
//!    subsequent writes replicate to the remaining nodes.
//!
//! The SQL surface is litewire's Hrana HTTP API (`hrana_listen`), because it
//! needs nothing beyond reqwest + JSON — no MySQL client, no PHP. The
//! clustered CDC path serves Hrana from the same wire factory as the MySQL
//! frontend, so what this suite observes is the replicated database.
//!
//! Environment:
//! - `EPHPM_BINARY` — path to an ephpm binary. Unset ⇒ the suite self-skips
//!   (so a bare `cargo test` still compiles and passes without a build).
//!
//! Skipped on Windows: clustered mode is Linux/macOS + experimental (see
//! CLAUDE.md, "Windows database").
//!
//! Deadlines are generous on purpose: the election heartbeats every 5s with a
//! 10s TTL, gossip failure detection adds its own delay, and CI runners are
//! slow. Every wait polls against a deadline — never sleep-and-hope.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

use anyhow::{Context, Result, anyhow, bail};
use ephpm_e2e::ephpm_binary_env;
use serde_json::json;
use tempfile::TempDir;

/// Shared secret for the fixture cluster. Fixed is fine: throwaway loopback
/// processes, never production.
const CLUSTER_SECRET: &str = "turso-cdc-e2e-secret-not-for-production";

/// How often the pollers re-check a condition.
const POLL_INTERVAL: Duration = Duration::from_millis(500);

/// Per-node config. Mirrors the shape of the harness cluster template
/// (`xtask/src/e2e_bare.rs::CLUSTER_NODE_TEMPLATE`) but is deliberately a
/// **private copy**: this suite's topology needs (`hrana_listen`, deferred
/// spawn, kill) must never leak into the shared template (issues #288/#295).
const NODE_TEMPLATE: &str = r#"# Auto-generated by the turso_cdc e2e suite — do not edit.
[server]
listen = "127.0.0.1:{HTTP_PORT}"
document_root = "{DOCROOT}"
index_files = ["index.html"]

[server.request]
trusted_hosts = ["localhost", "127.0.0.1", "127.0.0.1:{HTTP_PORT}"]

[server.metrics]
enabled = true

[db.sqlite]
path = "{DATA_DIR}/cdc.db"

[db.sqlite.proxy]
mysql_listen = "127.0.0.1:{MYSQL_PORT}"
hrana_listen = "127.0.0.1:{HRANA_PORT}"

[db.sqlite.replication]
role = "auto"

[cluster]
enabled = true
bind = "127.0.0.1:{GOSSIP_PORT}"
join = [{CLUSTER_JOIN}]
node_id = "{NODE_ID}"
cluster_id = "ephpm-e2e-turso-cdc"
secret = "{SECRET}"

[cluster.kv]
data_port = {KV_DATA_PORT}
"#;

struct NodePorts {
    http: u16,
    mysql: u16,
    hrana: u16,
    gossip: u16,
    kv_data: u16,
}

struct CdcCluster {
    binary: PathBuf,
    docroot: PathBuf,
    ports: Vec<NodePorts>,
    /// `Some(child)` while the node runs; `None` before spawn and after kill.
    children: Vec<Option<Child>>,
    tempdir: TempDir,
}

impl CdcCluster {
    /// Reserve port sets for `total` nodes (spawning none yet) and prepare
    /// the scratch layout. Ports for *every* node — including ones spawned
    /// later — are reserved up front so each node's `join` list can name the
    /// full eventual membership.
    async fn prepare(binary: &Path, total: usize) -> Result<Self> {
        let tempdir =
            tempfile::Builder::new().prefix("ephpm-e2e-cdc-").tempdir().context("tempdir")?;
        let docroot = tempdir.path().join("docroot");
        fs::create_dir_all(&docroot).context("create docroot")?;
        fs::write(docroot.join("index.html"), "cdc-e2e").context("write index.html")?;

        let mut ports = Vec::with_capacity(total);
        for _ in 0..total {
            ports.push(NodePorts {
                http: reserve_port().await?,
                mysql: reserve_port().await?,
                hrana: reserve_port().await?,
                gossip: reserve_gossip_port().await?,
                kv_data: reserve_port().await?,
            });
        }

        let mut children = Vec::with_capacity(total);
        children.resize_with(total, || None);
        Ok(Self { binary: binary.to_path_buf(), docroot, ports, children, tempdir })
    }

    /// Spawn node `i` and wait for its health endpoint.
    async fn spawn(&mut self, i: usize) -> Result<()> {
        assert!(self.children[i].is_none(), "node {i} already running");

        let node_dir = self.tempdir.path().join(format!("node-{i}"));
        let data_dir = node_dir.join("data");
        fs::create_dir_all(&data_dir).context("create data dir")?;

        let join = self
            .ports
            .iter()
            .enumerate()
            .filter(|(j, _)| *j != i)
            .map(|(_, p)| format!("\"127.0.0.1:{}\"", p.gossip))
            .collect::<Vec<_>>()
            .join(", ");

        let p = &self.ports[i];
        let config = NODE_TEMPLATE
            .replace("{HTTP_PORT}", &p.http.to_string())
            .replace("{MYSQL_PORT}", &p.mysql.to_string())
            .replace("{HRANA_PORT}", &p.hrana.to_string())
            .replace("{GOSSIP_PORT}", &p.gossip.to_string())
            .replace("{KV_DATA_PORT}", &p.kv_data.to_string())
            .replace("{NODE_ID}", &format!("cdc-node-{i}"))
            .replace("{CLUSTER_JOIN}", &join)
            .replace("{SECRET}", CLUSTER_SECRET)
            .replace("{DATA_DIR}", &escape_toml(&data_dir))
            .replace("{DOCROOT}", &escape_toml(&self.docroot));

        let config_path = node_dir.join("ephpm.toml");
        fs::write(&config_path, config).context("write config")?;
        let stdout = fs::File::create(node_dir.join("stdout.log")).context("stdout log")?;
        let stderr = fs::File::create(node_dir.join("stderr.log")).context("stderr log")?;

        eprintln!("[cdc-e2e] spawning node {i} (http 127.0.0.1:{})", p.http);
        let child = Command::new(&self.binary)
            .args(["serve", "--config"])
            .arg(&config_path)
            .stdout(Stdio::from(stdout))
            .stderr(Stdio::from(stderr))
            .spawn()
            .with_context(|| format!("spawn node {i} ({})", self.binary.display()))?;
        self.children[i] = Some(child);

        self.wait_healthy(i, Duration::from_secs(30)).await
    }

    /// Kill node `i` hard (SIGKILL / TerminateProcess) — this is the crash
    /// the failover phase is about, so no graceful shutdown.
    fn kill(&mut self, i: usize) {
        if let Some(mut child) = self.children[i].take() {
            eprintln!("[cdc-e2e] killing node {i}");
            let _ = child.kill();
            let _ = child.wait();
        }
    }

    async fn wait_healthy(&self, i: usize, timeout: Duration) -> Result<()> {
        let url = format!("http://127.0.0.1:{}/_ephpm/health", self.ports[i].http);
        let deadline = Instant::now() + timeout;
        let client = reqwest::Client::new();
        let mut last = String::from("no attempt");
        while Instant::now() < deadline {
            match client.get(&url).timeout(Duration::from_secs(2)).send().await {
                Ok(resp) if resp.status().as_u16() == 200 => return Ok(()),
                Ok(resp) => last = format!("HTTP {}", resp.status()),
                Err(e) => last = e.to_string(),
            }
            tokio::time::sleep(POLL_INTERVAL).await;
        }
        Err(anyhow!("node {i} never became healthy within {timeout:?}: {last}"))
    }

    /// Read one unlabeled metric from node `i`'s Prometheus endpoint.
    ///
    /// `None` when the node is unreachable or the series is absent — callers
    /// poll, so "not yet" and "not exposed" are the same answer.
    async fn metric(&self, i: usize, name: &str) -> Option<f64> {
        let url = format!("http://127.0.0.1:{}/metrics", self.ports[i].http);
        let client = reqwest::Client::new();
        let resp = client.get(&url).timeout(Duration::from_secs(2)).send().await.ok()?;
        let text = resp.text().await.ok()?;
        parse_metric(&text, name)
    }

    /// Poll until exactly one of `alive` reports
    /// `ephpm_cdc_subscribers == alive.len() - 1` while every other alive
    /// node reports 0. Returns the primary's node index.
    ///
    /// That condition is the whole phase-1 assertion in one shape: a sole
    /// primary exists, *and* every replica has attached to it (subscribers is
    /// the count of live replication streams, so this cannot pass on a
    /// half-formed cluster).
    async fn wait_for_sole_primary(&self, alive: &[usize], timeout: Duration) -> usize {
        let expected = to_f64(alive.len() - 1);
        let deadline = Instant::now() + timeout;
        let mut last_seen = String::new();
        loop {
            let mut subs = Vec::with_capacity(alive.len());
            for &i in alive {
                subs.push((i, self.metric(i, "ephpm_cdc_subscribers").await));
            }
            last_seen = format!("{subs:?}");

            let full: Vec<usize> = subs
                .iter()
                .filter(|(_, s)| *s == Some(expected))
                .map(|(i, _)| *i)
                .collect();
            let rest_zero = subs
                .iter()
                .filter(|(i, _)| !full.contains(i))
                .all(|(_, s)| *s == Some(0.0));
            if full.len() == 1 && rest_zero {
                eprintln!("[cdc-e2e] sole primary: node {} (subscribers {subs:?})", full[0]);
                return full[0];
            }

            assert!(
                Instant::now() < deadline,
                "no sole primary with {expected} attached replicas emerged within {timeout:?}; \
                 last ephpm_cdc_subscribers: {last_seen}"
            );
            tokio::time::sleep(POLL_INTERVAL).await;
        }
    }

    /// Execute one statement over node `i`'s Hrana HTTP endpoint.
    async fn sql(&self, i: usize, sql: &str) -> Result<serde_json::Value> {
        let url = format!("http://127.0.0.1:{}/v3/pipeline", self.ports[i].hrana);
        let body = json!({
            "requests": [
                { "type": "execute", "stmt": { "sql": sql } },
                { "type": "close" }
            ]
        });
        let resp = reqwest::Client::new()
            .post(&url)
            .json(&body)
            .timeout(Duration::from_secs(10))
            .send()
            .await
            .with_context(|| format!("POST {url}"))?;
        if !resp.status().is_success() {
            bail!("hrana on node {i} returned HTTP {}", resp.status());
        }
        let v: serde_json::Value = resp.json().await.context("hrana response json")?;
        if let Some(results) = v["results"].as_array() {
            for r in results {
                if r["type"] == "error" {
                    bail!(
                        "hrana statement error on node {i}: {}",
                        r["error"]["message"].as_str().unwrap_or("unknown")
                    );
                }
            }
        }
        Ok(v)
    }

    /// Execute a statement that must succeed (panics with context otherwise).
    async fn sql_ok(&self, i: usize, sql: &str) {
        self.sql(i, sql).await.unwrap_or_else(|e| panic!("SQL on node {i} failed: {e:#}\n  {sql}"));
    }

    /// Poll node `i` until `sql`'s first result column equals `want`.
    async fn wait_for_rows(&self, i: usize, sql: &str, want: &[&str], timeout: Duration, what: &str) {
        let deadline = Instant::now() + timeout;
        let mut last = String::from("no attempt");
        loop {
            match self.sql(i, sql).await {
                Ok(v) => {
                    let got = first_column(&v);
                    if got == want {
                        eprintln!("[cdc-e2e] node {i}: {what} — converged ({got:?})");
                        return;
                    }
                    last = format!("rows {got:?}");
                }
                Err(e) => last = format!("error: {e:#}"),
            }
            assert!(
                Instant::now() < deadline,
                "{what}: node {i} never converged to {want:?} within {timeout:?}; last: {last}"
            );
            tokio::time::sleep(POLL_INTERVAL).await;
        }
    }
}

impl Drop for CdcCluster {
    fn drop(&mut self) {
        let dump = std::thread::panicking();
        for i in 0..self.children.len() {
            self.kill(i);
        }
        if dump {
            for i in 0..self.children.len() {
                let log = self.tempdir.path().join(format!("node-{i}")).join("stderr.log");
                if let Ok(contents) = fs::read_to_string(&log) {
                    eprintln!("--- [cdc-e2e] node {i} stderr (last 60 lines) ---");
                    let lines: Vec<&str> = contents.lines().collect();
                    let start = lines.len().saturating_sub(60);
                    for line in &lines[start..] {
                        eprintln!("{line}");
                    }
                    eprintln!("--- end node {i} stderr ---");
                }
            }
        }
    }
}

// ── helpers ─────────────────────────────────────────────────────────────────

/// Ask the kernel for a free loopback port. Inherent TOCTOU, acceptable for a
/// fixture that spawns immediately after reserving.
async fn reserve_port() -> Result<u16> {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.context("bind :0")?;
    Ok(listener.local_addr().context("local_addr")?.port())
}

/// Reserve a gossip port whose derived cluster-channel port (`gossip + 2` —
/// see `ephpm_cluster::cluster_channel`) is also currently free, so the CDC
/// transport can bind.
async fn reserve_gossip_port() -> Result<u16> {
    for _ in 0..16 {
        let p = reserve_port().await?;
        if p >= u16::MAX - 2 {
            continue;
        }
        if tokio::net::TcpListener::bind(("127.0.0.1", p + 2)).await.is_ok() {
            return Ok(p);
        }
    }
    bail!("could not reserve a gossip port with a free channel port (+2)")
}

fn escape_toml(path: &Path) -> String {
    let mut out = String::new();
    for ch in path.to_string_lossy().chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c if c.is_control() => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Value of the first unlabeled Prometheus series named exactly `name`.
fn parse_metric(text: &str, name: &str) -> Option<f64> {
    text.lines()
        .filter(|l| !l.starts_with('#'))
        .find(|l| l.split_whitespace().next() == Some(name))
        .and_then(|l| l.split_whitespace().last())
        .and_then(|v| v.parse().ok())
}

/// First column of the first statement's result rows, as strings.
fn first_column(v: &serde_json::Value) -> Vec<String> {
    let Some(rows) = v["results"][0]["response"]["result"]["rows"].as_array() else {
        return Vec::new();
    };
    rows.iter()
        .map(|row| {
            let cell = &row[0];
            cell["value"]
                .as_str()
                .map_or_else(|| cell["value"].to_string(), std::string::ToString::to_string)
        })
        .collect()
}

#[allow(clippy::cast_precision_loss)]
fn to_f64(n: usize) -> f64 {
    n as f64
}

// ── the test ────────────────────────────────────────────────────────────────

/// One cluster, four phases: election → replication → cold bootstrap →
/// failover. A single test on purpose: the later phases *depend* on the
/// earlier ones (bootstrap needs pre-existing data; failover needs an
/// attached survivor), and one shared topology keeps the suite's process
/// count and wall time sane.
#[tokio::test(flavor = "multi_thread")]
async fn clustered_cdc_lifecycle() {
    if cfg!(windows) {
        eprintln!("clustered Turso CDC is not validated on Windows — skipping");
        return;
    }
    let Some(binary) = ephpm_binary_env() else {
        eprintln!("EPHPM_BINARY not set — skipping (needs a built ephpm binary)");
        return;
    };

    // Four port sets: three initial nodes plus the deferred cold node.
    let mut cluster = CdcCluster::prepare(&binary, 4).await.expect("prepare fixture");
    for i in 0..3 {
        cluster.spawn(i).await.unwrap_or_else(|e| panic!("start node {i}: {e:#}"));
    }

    // ── Phase 1: exactly one primary, both replicas attached ────────────
    let primary = cluster.wait_for_sole_primary(&[0, 1, 2], Duration::from_secs(90)).await;
    let replicas: Vec<usize> = (0..3).filter(|&i| i != primary).collect();

    // ── Phase 2: writes on the primary reach both replicas ──────────────
    cluster
        .sql_ok(primary, "CREATE TABLE cdc_e2e (id INTEGER PRIMARY KEY, v TEXT)")
        .await;
    cluster
        .sql_ok(primary, "INSERT INTO cdc_e2e (id, v) VALUES (1, 'alpha'), (2, 'beta')")
        .await;
    for &r in &replicas {
        cluster
            .wait_for_rows(
                r,
                "SELECT v FROM cdc_e2e ORDER BY id",
                &["alpha", "beta"],
                Duration::from_secs(60),
                "phase 2: primary write replicates",
            )
            .await;
    }

    // ── Phase 3: cold node joins after data exists (snapshot bootstrap) ─
    cluster.spawn(3).await.unwrap_or_else(|e| panic!("start cold node 3: {e:#}"));
    cluster
        .wait_for_rows(
            3,
            "SELECT v FROM cdc_e2e ORDER BY id",
            &["alpha", "beta"],
            Duration::from_secs(120),
            "phase 3: cold replica bootstraps pre-existing data",
        )
        .await;
    // ...and stays caught up via the post-snapshot tail.
    cluster.sql_ok(primary, "INSERT INTO cdc_e2e (id, v) VALUES (3, 'gamma')").await;
    cluster
        .wait_for_rows(
            3,
            "SELECT v FROM cdc_e2e ORDER BY id",
            &["alpha", "beta", "gamma"],
            Duration::from_secs(60),
            "phase 3: cold replica tails post-snapshot writes",
        )
        .await;

    // ── Phase 4: kill the primary; writes continue on the new one ───────
    cluster.kill(primary);
    let survivors: Vec<usize> = (0..4).filter(|&i| i != primary).collect();
    let new_primary = cluster.wait_for_sole_primary(&survivors, Duration::from_secs(120)).await;
    assert_ne!(new_primary, primary, "the dead primary cannot win the re-election");

    cluster.sql_ok(new_primary, "INSERT INTO cdc_e2e (id, v) VALUES (4, 'delta')").await;
    for &s in survivors.iter().filter(|&&s| s != new_primary) {
        cluster
            .wait_for_rows(
                s,
                "SELECT v FROM cdc_e2e ORDER BY id",
                &["alpha", "beta", "gamma", "delta"],
                Duration::from_secs(90),
                "phase 4: post-failover write replicates to the survivor",
            )
            .await;
    }
}
