//! Test fixture (not a shipped module): a middleware cdylib that declares
//! itself built against ABI **major 2** — the shape of an out-of-tree module
//! compiled after a future breaking change to the host table.
//!
//! The exports are hand-written rather than generated by
//! [`ephpm_middleware::declare!`] for one reason: the macro can only ever emit
//! the major it was compiled with, so it cannot express a version skew. The
//! `init` gate below is a byte-for-byte copy of the one `declare!` generates,
//! with the major bumped — see `crates/ephpm-middleware/src/lib.rs`:
//!
//! ```ignore
//! if (abi_version >> 24) != (abi::ABI_V1 >> 24) || host.is_null() { return -1; }
//! ```
//!
//! Mounting this module must abort server startup with a message naming the
//! mount and the refusal code — never load it. That is the failure this
//! fixture exists to pin down: a silently loaded module whose struct layout
//! disagrees with the host's is memory corruption, not a bad request.
#![allow(unsafe_code)] // Speaks the C middleware ABI by hand; see module docs.

use std::os::raw::{c_char, c_int};

use ephpm_middleware::abi;

/// The ABI major this fixture pretends to have been built against: one past
/// whatever the host currently speaks, so the skew survives a real ABI bump.
const FUTURE_MAJOR: u32 = (abi::ABI_V1 >> 24) + 1;

/// Refuses any host whose ABI major is not [`FUTURE_MAJOR`] — i.e. every
/// host that exists today.
#[unsafe(no_mangle)]
unsafe extern "C" fn ephpm_middleware_init(
    abi_version: u32,
    _config_json: *const c_char,
    host: *const abi::EphpmHostV1,
) -> c_int {
    if (abi_version >> 24) != FUTURE_MAJOR || host.is_null() {
        return -1;
    }
    0
}

/// Unreachable in practice: `init` refuses every host that speaks ABI major 1,
/// and the loader never resolves past a failed `init`. Present because the
/// loader requires all three mandatory symbols before it calls `init` at all —
/// omitting it would make this fixture fail for the wrong reason.
#[unsafe(no_mangle)]
unsafe extern "C" fn ephpm_middleware_invoke(
    _request: *const abi::EphpmRequest,
    _response_out: *mut abi::EphpmResponse,
) -> c_int {
    -1
}

/// Present for the same reason as `invoke`.
#[unsafe(no_mangle)]
unsafe extern "C" fn ephpm_middleware_shutdown() {}
