// FFI crate — unsafe is inherent to PHP embedding. Safety invariants
// are documented with comments before each unsafe block.
#![allow(unsafe_code)]

pub mod kv_bridge;
pub mod request;
pub mod response;
pub mod sapi;
#[cfg(all(php_linked, target_os = "windows"))]
pub mod windows_dll;

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;

use request::PhpRequest;
use response::PhpResponse;

// When PHP_SDK_PATH is set at build time, build.rs enables the `php_linked` cfg
// and generates FFI bindings. This module includes them.
#[cfg(php_linked)]
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::all
)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/php_bindings.rs"));

    // Our C wrapper — compiled by cc in build.rs, not generated by bindgen.
    // Uses `zend_try`/`zend_catch` to safely handle PHP's setjmp/longjmp.
    unsafe extern "C" {
        /// Override default embed SAPI callbacks with our implementations.
        pub fn ephpm_install_sapi();

        /// Shut down the initial request started by `php_embed_init()`.
        /// Must be called after `ephpm_install_sapi()` so HTTP requests
        /// start from a clean state.
        pub fn ephpm_finalize_init();

        /// Apply INI settings (disable stack size checking).
        pub fn ephpm_apply_ini_settings() -> ::std::os::raw::c_int;

        /// Set a PHP INI directive for the current request.
        pub fn ephpm_request_set_ini(
            key: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        );

        /// Reset per-request state.
        pub fn ephpm_request_clear();

        /// Set core request info fields. Pointers must stay valid until
        /// `ephpm_execute_request` returns.
        pub fn ephpm_request_set_info(
            method: *const ::std::os::raw::c_char,
            uri: *const ::std::os::raw::c_char,
            query_string: *const ::std::os::raw::c_char,
            content_type: *const ::std::os::raw::c_char,
            cookie: *const ::std::os::raw::c_char,
            post_data: *const ::std::os::raw::c_char,
            post_data_len: usize,
            path_translated: *const ::std::os::raw::c_char,
        );

        /// Add a `$_SERVER` variable. Pointers must stay valid until
        /// `ephpm_execute_request` returns.
        pub fn ephpm_request_add_server_var(
            key: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        );

        /// Execute a PHP request with full lifecycle management.
        /// Returns 0 on success, -1 on startup failure, -2 on bailout.
        pub fn ephpm_execute_request(
            filename: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int;

        /// Get the captured output buffer. Sets `*out_len` to the length.
        pub fn ephpm_get_output_buf(
            out_len: *mut usize,
        ) -> *const ::std::os::raw::c_char;

        /// Get the HTTP response status code.
        pub fn ephpm_get_response_code() -> ::std::os::raw::c_int;

        /// Get the captured response headers ("Name: Value\n" lines).
        /// Sets `*out_len` to the length.
        pub fn ephpm_get_response_headers(
            out_len: *mut usize,
        ) -> *const ::std::os::raw::c_char;

        // ── ZTS thread lifecycle ────────────────────────────────────

        /// Initialize the current thread for PHP execution under ZTS.
        /// Registers with TSRM and starts a PHP request.
        /// Returns 0 on success, -1 on failure.
        /// NTS builds: no-op (returns 0).
        pub fn ephpm_thread_init() -> ::std::os::raw::c_int;

        /// Shut down PHP on the current thread.
        /// Performs request shutdown and unregisters from TSRM.
        /// NTS builds: no-op.
        pub fn ephpm_thread_shutdown();

        // ── CLI mode functions ──────────────────────────────────────

        /// Register `additional_functions` (KV native functions) on
        /// `php_embed_module`. Must be called BEFORE `php_embed_init()`.
        pub fn ephpm_pre_init();

        /// Set a custom php.ini file path. Must be called BEFORE
        /// `php_embed_init()` so the ini file is loaded during module startup.
        pub fn ephpm_set_ini_file(ini_file: *const ::std::os::raw::c_char);

        /// Set the KV ops function pointer table. Can be called after
        /// `php_embed_init()`, before any PHP scripts execute.
        pub fn ephpm_set_kv_ops(
            ops: *const crate::kv_bridge::EphpmKvOps,
        );

        /// Get the PHP version string (compile-time constant).
        /// Safe to call before `php_embed_init()`.
        pub fn ephpm_get_php_version() -> *const ::std::os::raw::c_char;

        /// PHP CLI main entry point. Parses argc/argv using php_getopt
        /// and dispatches to the appropriate PHP APIs. Call after
        /// `php_embed_init()`. Returns the process exit code.
        pub fn ephpm_cli_main(
            argc: ::std::os::raw::c_int,
            argv: *mut *mut ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int;
    }
}

/// Tracks whether the current thread has been registered with TSRM.
///
/// Each `spawn_blocking` thread must call `ephpm_thread_init()` once
/// before executing PHP. This thread-local avoids redundant registration.
#[cfg(php_linked)]
thread_local! {
    static THREAD_REGISTERED: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

#[derive(Debug, thiserror::Error)]
pub enum PhpError {
    /// PHP module initialization (`php_embed_init`) failed.
    #[error("PHP runtime failed to initialize")]
    InitFailed,

    /// A PHP script execution error (bailout, fatal, etc.).
    #[error("PHP script execution failed: {0}")]
    ExecutionFailed(String),

    /// The init/shutdown mutex was poisoned by a panic.
    #[error("PHP runtime lock poisoned")]
    LockPoisoned,

    /// `execute()` called before `init()`.
    #[error("PHP runtime not initialized")]
    NotInitialized,

    /// TSRM thread registration failed.
    #[error("PHP thread initialization failed")]
    ThreadInitFailed,
}

/// Wrapper around the PHP embed SAPI with ZTS (Zend Thread Safety).
///
/// PHP is built with `--enable-zts`, enabling TSRM (Thread Safe Resource
/// Manager). Each `spawn_blocking` thread registers with TSRM on first
/// use, getting its own copy of PHP global state. This allows concurrent
/// PHP execution across multiple threads.
///
/// The `Mutex` only protects `init()` / `shutdown()` (one-time lifecycle).
/// `execute()` runs lock-free on any registered thread.
pub struct PhpRuntime {
    initialized: bool,
}

/// Whether the PHP module has been initialized (set once by `init()`).
///
/// Checked by `execute()` without acquiring the mutex — the atomic
/// provides a fast-path "is PHP ready?" check.
static PHP_INITIALIZED: AtomicBool = AtomicBool::new(false);

/// Mutex protecting one-time `init()` / `shutdown()` lifecycle.
///
/// Not held during `execute()` — ZTS threads execute concurrently.
static PHP_RUNTIME: Mutex<Option<PhpRuntime>> = Mutex::new(None);

impl PhpRuntime {
    /// Initialize the PHP runtime.
    ///
    /// This must be called once before any PHP requests can be executed.
    /// When libphp is linked, calls `php_embed_init()` to set up the
    /// interpreter and installs our custom SAPI callbacks.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` if the runtime mutex is poisoned,
    /// or `PhpError::InitFailed` if PHP initialization fails.
    pub fn init() -> Result<(), PhpError> {
        Self::init_with_ini_file(None)
    }

    /// Initialize the PHP runtime with a custom ini file.
    ///
    /// If `ini_file` is `Some`, that file will be loaded before any PHP
    /// scripts execute. If `None`, PHP uses its default ini file search.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` if the runtime mutex is poisoned,
    /// or `PhpError::InitFailed` if PHP initialization fails.
    pub fn init_with_ini_file(_ini_file: Option<&std::path::Path>) -> Result<(), PhpError> {
        let mut runtime = PHP_RUNTIME.lock().map_err(|_| PhpError::LockPoisoned)?;
        if runtime.is_some() {
            return Ok(()); // Already initialized
        }

        #[cfg(php_linked)]
        {
            use std::ffi::CString;

            // Register KV native functions on php_embed_module.additional_functions.
            // Safety: Must be called before php_embed_init() so php_module_startup()
            // registers the functions. No PHP state exists yet.
            unsafe { ffi::ephpm_pre_init() };

            // Keep the CString alive until php_embed_init() completes so the
            // pointer remains valid while PHP reads the configuration.
            let _ini_file_cstring = if let Some(path) = _ini_file {
                let cstr = CString::new(path.to_string_lossy().into_owned())
                    .unwrap_or_else(|_| CString::new("").unwrap());
                // Safety: Must be called before php_embed_init() so the ini file
                // is loaded during module startup. The pointer is valid until
                // php_embed_init() returns.
                unsafe { ffi::ephpm_set_ini_file(cstr.as_ptr()) };
                Some(cstr)
            } else {
                None
            };

            // Initialize PHP embed SAPI (module + initial request startup).
            // Safety: php_embed_init must be called exactly once before any PHP
            // execution. We guarantee this via the Mutex + Option guard.
            let arg0 = CString::new("ephpm").unwrap();
            let mut argv_ptrs = [arg0.as_ptr().cast_mut(), std::ptr::null_mut()];
            // Safety: argv is valid, argc matches the number of non-null entries.
            let ret = unsafe { ffi::php_embed_init(1, argv_ptrs.as_mut_ptr()) };
            if ret != 0 {
                return Err(PhpError::InitFailed);
            }

            // Install our custom SAPI callbacks (ub_write, read_post, etc.)
            // Safety: Must be called after php_embed_init, before any requests.
            unsafe { ffi::ephpm_install_sapi() };

            // Apply INI settings (disable stack size checking for tokio threads)
            // Safety: Must be called after php_embed_init.
            unsafe { ffi::ephpm_apply_ini_settings() };

            tracing::info!("PHP runtime initialized (libphp linked)");
        }

        #[cfg(not(php_linked))]
        {
            tracing::info!("PHP runtime initialized (stub — no libphp linked)");
        }

        *runtime = Some(PhpRuntime { initialized: true });
        PHP_INITIALIZED.store(true, Ordering::Release);
        Ok(())
    }

    /// Shut down the PHP runtime.
    ///
    /// Calls `php_embed_shutdown()` and cleans up.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` if the runtime mutex is poisoned.
    pub fn shutdown() -> Result<(), PhpError> {
        let mut runtime = PHP_RUNTIME.lock().map_err(|_| PhpError::LockPoisoned)?;
        if let Some(rt) = runtime.take() {
            PHP_INITIALIZED.store(false, Ordering::Release);
            drop(rt);

            #[cfg(php_linked)]
            {
                // Safety: Paired with php_embed_init in init().
                // Handles request shutdown + module shutdown.
                unsafe { ffi::php_embed_shutdown() };
                tracing::info!("PHP runtime shut down");
            }

            #[cfg(not(php_linked))]
            {
                tracing::info!("PHP runtime shut down (stub)");
            }
        }
        Ok(())
    }

    /// Finalize initialization for HTTP serve mode.
    ///
    /// `php_embed_init()` starts a request automatically. This marks it as
    /// active so that the first call to `ephpm_execute_request()` properly
    /// shuts it down before starting its own request lifecycle.
    ///
    /// Must be called after [`init()`] and before the first HTTP request.
    /// Do NOT call this before using CLI mode (`cli_main`), which reuses
    /// the embed's initial request.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` if the runtime mutex is poisoned,
    /// or `PhpError::NotInitialized` if the runtime hasn't been initialized.
    pub fn finalize_for_http() -> Result<(), PhpError> {
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return Err(PhpError::NotInitialized);
        }

        #[cfg(php_linked)]
        {
            // Safety: Called once after init, marks the embed's initial request
            // as active so ephpm_execute_request shuts it down on first call.
            unsafe { ffi::ephpm_finalize_init() };
            tracing::debug!("PHP embed initial request marked active (ready for HTTP)");
        }

        Ok(())
    }

    // ── CLI mode methods ──────────────────────────────────────────────────

    /// Get the embedded PHP version string (e.g. "8.5.4").
    ///
    /// This reads a compile-time constant and does not require the PHP
    /// runtime to be initialized.
    #[cfg(php_linked)]
    #[must_use]
    pub fn php_version() -> &'static str {
        // Safety: ephpm_get_php_version returns a pointer to the static
        // PHP_VERSION string constant, which is valid for the entire process.
        let ptr = unsafe { ffi::ephpm_get_php_version() };
        // Safety: PHP_VERSION is a valid UTF-8 C string literal.
        unsafe { std::ffi::CStr::from_ptr(ptr) }
            .to_str()
            .unwrap_or("unknown")
    }

    /// Get the embedded PHP version string (stub mode).
    #[cfg(not(php_linked))]
    #[must_use]
    pub fn php_version() -> &'static str {
        "not available (stub mode — no libphp linked)"
    }

    /// Run the PHP CLI with the given arguments.
    ///
    /// Passes `args` through to PHP's argument parser, supporting all
    /// standard PHP CLI flags (`-v`, `-r`, `-f`, `-m`, `-i`, `-l`, etc.).
    /// Output goes directly to stdout/stderr.
    ///
    /// Initializes the PHP runtime if needed. Returns the PHP exit code
    /// (0 for success).
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` or `PhpError::InitFailed` on failure.
    pub fn cli_main(args: &[String]) -> Result<i32, PhpError> {
        Self::init()?;

        #[cfg(php_linked)]
        {
            use std::ffi::CString;

            // CLI mode uses the initial embed request context on the main thread.
            // Acquire the mutex to prevent concurrent CLI + HTTP mode.
            let _runtime = PHP_RUNTIME.lock().map_err(|_| PhpError::LockPoisoned)?;

            // Build argc/argv for the C function.
            // argv[0] is the program name, followed by the user's args.
            let mut c_args: Vec<CString> = Vec::with_capacity(args.len() + 1);
            c_args.push(CString::new("ephpm").unwrap());
            for arg in args {
                c_args.push(CString::new(arg.as_str()).map_err(|e| {
                    PhpError::ExecutionFailed(format!("invalid argument: {e}"))
                })?);
            }

            let mut argv_ptrs: Vec<*mut std::os::raw::c_char> =
                c_args.iter().map(|s| s.as_ptr().cast_mut()).collect();
            argv_ptrs.push(std::ptr::null_mut());

            let argc = c_args.len() as std::os::raw::c_int;

            // Safety: We hold the runtime lock. argv_ptrs is valid for argc
            // entries plus a null terminator. The C function handles request
            // lifecycle and bailout protection internally.
            let ret = unsafe { ffi::ephpm_cli_main(argc, argv_ptrs.as_mut_ptr()) };
            Ok(ret)
        }

        #[cfg(not(php_linked))]
        {
            let _ = args;
            Err(PhpError::ExecutionFailed(
                "PHP not linked — build with PHP_SDK_PATH to enable CLI mode".into(),
            ))
        }
    }

    // ── HTTP mode methods ────────────────────────────────────────────────

    /// Execute a PHP request.
    ///
    /// With ZTS, this runs **without** the global mutex — each
    /// `spawn_blocking` thread has its own TSRM-registered PHP context.
    /// On first call from a new thread, the thread is automatically
    /// registered with TSRM via `ephpm_thread_init()`.
    ///
    /// This function is designed to be called from `tokio::task::spawn_blocking`
    /// since it blocks the calling thread for the duration of PHP execution.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::NotInitialized` if the runtime hasn't been
    /// initialized, or `PhpError::ThreadInitFailed` if TSRM registration fails.
    #[allow(clippy::needless_pass_by_value)]
    pub fn execute(request: PhpRequest) -> Result<PhpResponse, PhpError> {
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return Err(PhpError::NotInitialized);
        }

        #[cfg(php_linked)]
        Self::ensure_thread_registered()?;

        tracing::debug!(
            method = %request.method,
            uri = %request.uri,
            script = %request.script_filename.display(),
            "executing PHP request"
        );

        #[cfg(php_linked)]
        {
            Self::execute_php(&request)
        }

        #[cfg(not(php_linked))]
        {
            // Stub response for development without libphp
            Ok(PhpResponse {
                status: 200,
                headers: vec![("Content-Type".to_string(), "text/html".to_string())],
                body: format!(
                    "<html><body>\
                     <h1>ePHPm Stub</h1>\
                     <p>PHP not linked. Would execute: {}</p>\
                     <p>Build with <code>PHP_SDK_PATH</code> set to enable PHP execution.</p>\
                     </body></html>",
                    request.script_filename.display()
                )
                .into_bytes(),
            })
        }
    }

    /// Ensure the current thread is registered with TSRM.
    ///
    /// Called on every `execute()` — fast-path is a thread-local check.
    /// Only the first call on each thread actually registers with TSRM.
    #[cfg(php_linked)]
    fn ensure_thread_registered() -> Result<(), PhpError> {
        THREAD_REGISTERED.with(|registered| {
            if registered.get() {
                return Ok(());
            }

            // SAFETY: PHP module has been initialized (checked via atomic above).
            // ephpm_thread_init() calls ts_resource(0) + php_request_startup(),
            // which are the correct TSRM registration sequence. The C function
            // uses zend_try/zend_catch internally for bailout protection.
            let ret = unsafe { ffi::ephpm_thread_init() };
            if ret != 0 {
                return Err(PhpError::ThreadInitFailed);
            }

            registered.set(true);
            tracing::debug!("TSRM thread registered for PHP execution");
            Ok(())
        })
    }

    /// Execute a PHP script via our custom SAPI bridge.
    ///
    /// Sets up per-request state in C, executes the script with proper
    /// request lifecycle management, and captures the response.
    #[cfg(php_linked)]
    fn execute_php(request: &PhpRequest) -> Result<PhpResponse, PhpError> {
        use std::ffi::CString;

        // Clear previous request state in the C wrapper's thread-local buffers.
        // SAFETY: The current thread is registered with TSRM and owns its
        // thread-local C state. No concurrent access to these buffers.
        unsafe { ffi::ephpm_request_clear() };

        // Prepare C strings for the request info.
        // These must stay alive until ephpm_execute_request returns.
        let method = CString::new(request.method.as_str())
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid method: {e}")))?;
        let uri = CString::new(request.uri.as_str())
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid URI: {e}")))?;
        let query_string = CString::new(request.query_string.as_str())
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid query string: {e}")))?;
        let content_type_str = request.content_type.as_deref().unwrap_or("");
        let content_type = CString::new(content_type_str)
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid content type: {e}")))?;
        let cookie = CString::new(request.cookie_string())
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid cookie: {e}")))?;
        let script_path = request
            .script_filename
            .to_str()
            .ok_or_else(|| PhpError::ExecutionFailed("non-UTF8 script path".into()))?;
        let script_filename = CString::new(script_path)
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid script path: {e}")))?;

        // Pass POST body — use null pointer for empty bodies
        let post_data_ptr = if request.body.is_empty() {
            std::ptr::null()
        } else {
            request.body.as_ptr().cast()
        };

        // Set core request info in C
        // Safety: All CString pointers are valid and will stay alive.
        unsafe {
            ffi::ephpm_request_set_info(
                method.as_ptr(),
                uri.as_ptr(),
                query_string.as_ptr(),
                content_type.as_ptr(),
                cookie.as_ptr(),
                post_data_ptr,
                request.body.len(),
                script_filename.as_ptr(),
            );
        }

        // Build and pass server variables ($_SERVER)
        let server_vars = request.server_variables();
        let c_server_vars: Vec<(CString, CString)> = server_vars
            .iter()
            .filter_map(|(k, v)| {
                Some((CString::new(k.as_str()).ok()?, CString::new(v.as_str()).ok()?))
            })
            .collect();

        for (key, value) in &c_server_vars {
            // Safety: CString pointers are valid and stay alive.
            unsafe {
                ffi::ephpm_request_add_server_var(key.as_ptr(), value.as_ptr());
            }
        }

        // Execute the PHP request on this thread's TSRM context.
        // SAFETY: This thread is registered with TSRM. All PHP globals
        // accessed by ephpm_execute_request are thread-local under ZTS.
        // The C function uses setjmp/longjmp bailout protection.
        let ret = unsafe { ffi::ephpm_execute_request(script_filename.as_ptr()) };

        // Retrieve the captured response from C
        let body = {
            let mut len: usize = 0;
            // Safety: out_len pointer is valid.
            let ptr = unsafe { ffi::ephpm_get_output_buf(&mut len) };
            if ptr.is_null() || len == 0 {
                Vec::new()
            } else {
                // Safety: ptr is valid for len bytes (managed by C output buffer).
                unsafe { std::slice::from_raw_parts(ptr.cast::<u8>(), len) }.to_vec()
            }
        };

        // Safety: No arguments, returns a simple int.
        let status_code = unsafe { ffi::ephpm_get_response_code() };

        let headers = {
            let mut len: usize = 0;
            // Safety: out_len pointer is valid.
            let ptr = unsafe { ffi::ephpm_get_response_headers(&mut len) };
            if ptr.is_null() || len == 0 {
                Vec::new()
            } else {
                // Safety: ptr is valid for len bytes (managed by C headers buffer).
                let raw = unsafe { std::slice::from_raw_parts(ptr.cast::<u8>(), len) };
                // Headers are "Name: Value\n" lines. Parse them.
                String::from_utf8_lossy(raw)
                    .lines()
                    .filter_map(|line| {
                        let (name, value) = line.split_once(": ")?;
                        Some((name.to_string(), value.to_string()))
                    })
                    .collect()
            }
        };

        let status = u16::try_from(status_code).unwrap_or(200);

        match ret {
            0 => Ok(PhpResponse { status, headers, body }),
            -1 => Err(PhpError::ExecutionFailed(
                "php_request_startup failed".into(),
            )),
            _ => {
                // Bailout (exit/die/fatal): return whatever output was captured
                if body.is_empty() {
                    Err(PhpError::ExecutionFailed(
                        "PHP bailout (fatal error or exit)".into(),
                    ))
                } else {
                    // exit() and die() are common in PHP — return the output
                    Ok(PhpResponse { status, headers, body })
                }
            }
        }
    }

    /// Register the KV store so PHP native `ephpm_kv_*` functions can
    /// access it.
    ///
    /// Must be called after [`init()`] (so the PHP runtime exists) and
    /// before any PHP requests execute. Typically called from
    /// `ephpm-server` after creating the [`ephpm_kv::store::Store`].
    ///
    /// In stub mode (no `php_linked`), this is a no-op.
    pub fn set_kv_store(store: &std::sync::Arc<ephpm_kv::store::Store>) {
        #[cfg(php_linked)]
        {
            kv_bridge::set_store(std::sync::Arc::clone(store));

            // Safety: KV_OPS is a static with stable address. ephpm_set_kv_ops
            // copies the struct into the C global — the pointer only needs to be
            // valid for the duration of this call.
            unsafe { ffi::ephpm_set_kv_ops(&kv_bridge::KV_OPS) };

            tracing::info!("KV store wired to PHP native functions");
        }

        #[cfg(not(php_linked))]
        {
            let _ = store;
            tracing::debug!("KV store set_kv_store no-op (stub mode)");
        }
    }

    /// Set a PHP INI directive for the current request.
    ///
    /// Must be called on a TSRM-registered thread (inside `spawn_blocking`)
    /// before `execute()`. Uses `PHP_INI_SYSTEM` so the value cannot be
    /// overridden by userland `ini_set()`.
    ///
    /// Common use: `open_basedir` and `disable_functions` for vhost isolation.
    #[cfg(php_linked)]
    pub fn set_request_ini(key: &str, value: &str) {
        let c_key = std::ffi::CString::new(key).expect("INI key contains null byte");
        let c_val = std::ffi::CString::new(value).expect("INI value contains null byte");
        // SAFETY: c_key and c_val are valid null-terminated C strings.
        // ephpm_request_set_ini copies the data via zend_string_init.
        // Under ZTS, this modifies the current thread's INI entries only.
        #[allow(unsafe_code)]
        unsafe {
            ffi::ephpm_request_set_ini(c_key.as_ptr(), c_val.as_ptr());
        }
    }

    /// Stub when PHP is not linked.
    #[cfg(not(php_linked))]
    pub fn set_request_ini(_key: &str, _value: &str) {}
}

impl Drop for PhpRuntime {
    fn drop(&mut self) {
        if self.initialized {
            tracing::debug!("PhpRuntime dropped");
        }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use serial_test::serial;

    use super::*;

    fn make_test_request() -> PhpRequest {
        PhpRequest {
            method: "GET".into(),
            uri: "/test.php".into(),
            path: "/test.php".into(),
            query_string: String::new(),
            script_filename: PathBuf::from("/var/www/html/test.php"),
            document_root: PathBuf::from("/var/www/html"),
            headers: Vec::new(),
            body: Vec::new(),
            content_type: None,
            remote_addr: "127.0.0.1:12345".parse().unwrap(),
            server_name: "localhost".into(),
            server_port: 8080,
            is_https: false,
            protocol: "HTTP/1.1".into(),
            env_vars: Vec::new(),
        }
    }

    #[test]
    #[serial]
    fn test_stub_init_succeeds() {
        let _ = PhpRuntime::shutdown();
        assert!(PhpRuntime::init().is_ok());
        let _ = PhpRuntime::shutdown();
    }

    #[test]
    #[serial]
    fn test_stub_init_is_idempotent() {
        let _ = PhpRuntime::shutdown();
        assert!(PhpRuntime::init().is_ok());
        assert!(PhpRuntime::init().is_ok());
        let _ = PhpRuntime::shutdown();
    }

    #[test]
    #[serial]
    fn test_stub_shutdown_after_init() {
        let _ = PhpRuntime::shutdown();
        PhpRuntime::init().unwrap();
        assert!(PhpRuntime::shutdown().is_ok());
    }

    #[test]
    #[serial]
    fn test_stub_shutdown_without_init() {
        let _ = PhpRuntime::shutdown();
        // Shutdown on an already-empty runtime should be a no-op
        assert!(PhpRuntime::shutdown().is_ok());
    }

    #[test]
    #[serial]
    fn test_stub_execute_returns_stub_html() {
        let _ = PhpRuntime::shutdown();
        PhpRuntime::init().unwrap();

        let response = PhpRuntime::execute(make_test_request()).unwrap();
        assert_eq!(response.status, 200);
        assert!(response
            .headers
            .iter()
            .any(|(k, v)| k == "Content-Type" && v == "text/html"));
        let body = String::from_utf8(response.body).unwrap();
        assert!(body.contains("ePHPm Stub"));
        assert!(body.contains("test.php"));

        let _ = PhpRuntime::shutdown();
    }

    #[test]
    #[serial]
    fn test_stub_execute_without_init_returns_not_initialized() {
        let _ = PhpRuntime::shutdown();

        let err = PhpRuntime::execute(make_test_request()).unwrap_err();
        assert!(
            matches!(err, PhpError::NotInitialized),
            "expected NotInitialized, got {err}"
        );
    }
}
