// FFI crate — unsafe is inherent to PHP embedding. Safety invariants
// are documented with comments before each unsafe block.
#![allow(unsafe_code)]

pub mod crash_guard;
pub mod db_bridge;
pub mod kv_bridge;
pub mod request;
pub mod response;
pub mod sapi;
pub mod worker_bridge;
pub mod ws_bridge;

use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, Ordering};

use request::PhpRequest;
use response::PhpResponse;

// When PHP_SDK_PATH is set at build time, build.rs enables the `php_linked` cfg
// and generates FFI bindings. This module includes them.
#[cfg(php_linked)]
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::all
)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/php_bindings.rs"));

    // Our C wrapper — compiled by cc in build.rs, not generated by bindgen.
    // Uses `zend_try`/`zend_catch` to safely handle PHP's setjmp/longjmp.
    unsafe extern "C" {
        /// Override default embed SAPI callbacks with our implementations.
        pub fn ephpm_install_sapi();

        /// Shut down the initial request started by `php_embed_init()`.
        /// Must be called after `ephpm_install_sapi()` so HTTP requests
        /// start from a clean state.
        pub fn ephpm_finalize_init();

        /// Apply INI settings (disable stack size checking).
        pub fn ephpm_apply_ini_settings() -> ::std::os::raw::c_int;

        /// Set a PHP INI directive for the current request.
        pub fn ephpm_request_set_ini(
            key: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        );

        /// Reset per-request state.
        pub fn ephpm_request_clear();

        /// Set core request info fields. Pointers must stay valid until
        /// `ephpm_execute_request` returns.
        pub fn ephpm_request_set_info(
            method: *const ::std::os::raw::c_char,
            uri: *const ::std::os::raw::c_char,
            query_string: *const ::std::os::raw::c_char,
            content_type: *const ::std::os::raw::c_char,
            cookie: *const ::std::os::raw::c_char,
            post_data: *const ::std::os::raw::c_char,
            post_data_len: usize,
            path_translated: *const ::std::os::raw::c_char,
        );

        /// Add a `$_SERVER` variable. Pointers must stay valid until
        /// `ephpm_execute_request` returns.
        pub fn ephpm_request_add_server_var(
            key: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        );

        /// Execute a PHP request with full lifecycle management.
        ///
        /// Returns one of the `EPHPM_EXEC_*` codes defined in
        /// `ephpm_wrapper.c` — mirrored by `super::exec_code`.
        pub fn ephpm_execute_request(
            filename: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int;

        /// Get the captured output buffer. Sets `*out_len` to the length.
        pub fn ephpm_get_output_buf(out_len: *mut usize) -> *const ::std::os::raw::c_char;

        /// Get the HTTP response status code.
        pub fn ephpm_get_response_code() -> ::std::os::raw::c_int;

        /// Get the captured response headers ("Name: Value\n" lines).
        /// Sets `*out_len` to the length.
        pub fn ephpm_get_response_headers(out_len: *mut usize) -> *const ::std::os::raw::c_char;

        // ── ZTS thread lifecycle ────────────────────────────────────

        /// Initialize the current thread for PHP execution under ZTS.
        /// Registers with TSRM and starts a PHP request.
        /// Returns 0 on success, -1 on failure.
        /// NTS builds: no-op (returns 0).
        pub fn ephpm_thread_init() -> ::std::os::raw::c_int;

        /// Shut down PHP on the current thread.
        /// Performs request shutdown and unregisters from TSRM.
        /// NTS builds: no-op.
        pub fn ephpm_thread_shutdown();

        // ── CLI mode functions ──────────────────────────────────────

        /// Install our embed module-startup shim so the KV native functions
        /// (`ephpm_kv_get` etc.) get registered during PHP's module init.
        /// Must be called BEFORE `php_embed_init()` — see the C wrapper for
        /// the full ZTS-aware rationale.
        pub fn ephpm_pre_init();

        /// Set a custom php.ini file path. Must be called BEFORE
        /// `php_embed_init()` so the ini file is loaded during module startup.
        /// Also backs the CLI `-c <path>` flag.
        pub fn ephpm_set_ini_file(ini_file: *const ::std::os::raw::c_char);

        /// Report the SAPI as `"cli"` (so `PHP_SAPI` / `php_sapi_name()` return
        /// `"cli"`) for the `ephpm php` process. Must be called BEFORE
        /// `php_embed_init()`. The server never calls this and stays `"ephpm"`.
        pub fn ephpm_enable_cli_mode();

        /// CLI `-n` — load no php.ini file at all. Must be called BEFORE
        /// `php_embed_init()` (the ini search happens during module startup).
        pub fn ephpm_cli_set_no_ini();

        /// CLI `-d name[=value]` — record one ini directive for startup-time
        /// application (spliced into `sapi_module.ini_entries` before
        /// `php_module_startup()`, exactly as php-cli applies `-d`). Must be
        /// called BEFORE `php_embed_init()`: MINIT-time consumers (OPcache's
        /// enable/enable_cli/JIT decision, `extension=` loading) read the
        /// value during module startup and never again (issue #331). The
        /// string is copied immediately; the pointer need not outlive the
        /// call.
        pub fn ephpm_cli_add_ini_define(def: *const ::std::os::raw::c_char);

        /// Set the configured `max_execution_time` (seconds) the request paths
        /// use to arm PHP's per-thread execution timer. Necessary because the
        /// embed SAPI resets the `max_execution_time` ini entry to `0`
        /// (unlimited) at runtime, so we cannot rely on the ini→timer chain and
        /// must arm explicitly from this value each request. On builds without
        /// per-thread timers this is a no-op. Call after `php_embed_init()`.
        pub fn ephpm_set_max_execution_time(secs: ::std::os::raw::c_long);

        /// Set the KV ops function pointer table. Can be called after
        /// `php_embed_init()`, before any PHP scripts execute.
        pub fn ephpm_set_kv_ops(ops: *const crate::kv_bridge::EphpmKvOps);

        /// Set the DB ops function pointer table backing the native
        /// `ephpm_db_*` functions. Same timing contract as
        /// `ephpm_set_kv_ops`.
        pub fn ephpm_set_db_ops(ops: *const crate::db_bridge::EphpmDbOps);

        /// Set the WebSocket ops function pointer table backing the native
        /// `ephpm_ws_*` functions. Same timing contract as
        /// `ephpm_set_kv_ops`.
        pub fn ephpm_set_ws_ops(ops: *const crate::ws_bridge::EphpmWsOps);

        // ── Worker mode ─────────────────────────────────────────────

        /// Set the worker ops function pointer table (`take_request` /
        /// `send_response`). Call after `php_embed_init()`, before any worker
        /// boots.
        pub fn ephpm_set_worker_ops(ops: *const crate::worker_bridge::EphpmWorkerOps);

        /// Toggle native superglobal population per request in worker mode
        /// (`worker.populate_superglobals`). `0` = off (default), `1` = on.
        pub fn ephpm_worker_set_populate_superglobals(enable: ::std::os::raw::c_int);

        /// Boot a worker: run the worker script under bailout protection. Blocks
        /// until the framework's `take_request()` loop ends. Returns 0 on a
        /// clean loop end, -2 if a fatal bailout unwound out of the framework.
        pub fn ephpm_worker_run(script: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;

        /// Get the PHP version string (compile-time constant).
        /// Safe to call before `php_embed_init()`.
        pub fn ephpm_get_php_version() -> *const ::std::os::raw::c_char;

        /// PHP CLI main entry point. Parses argc/argv using php_getopt
        /// and dispatches to the appropriate PHP APIs. Call after
        /// `php_embed_init()`. Returns the process exit code.
        pub fn ephpm_cli_main(
            argc: ::std::os::raw::c_int,
            argv: *mut *mut ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int;

        // ── OPcache clustered invalidation (phase 1) ──────────────────

        /// Walk `opcache_get_status(true)['scripts']` and invalidate every
        /// cached entry whose path starts with `docroot`.
        ///
        /// Returns the number of scripts invalidated on success, `-1` when
        /// OPcache is not available or a bailout occurred. Must be called on
        /// a TSRM-registered thread with an active PHP request context.
        pub fn ephpm_opcache_invalidate_under(
            docroot: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_long;

        /// Class+message of the last exception observed by the invalidator
        /// on this thread ("Class: msg"; empty string when none).
        pub fn ephpm_opcache_last_exception() -> *const ::std::os::raw::c_char;
    }
}

/// Tracks whether the current thread has been registered with TSRM, and
/// retires the thread's PHP context when the thread exits.
///
/// Each `spawn_blocking` thread must call `ephpm_thread_init()` once
/// before executing PHP. This thread-local avoids redundant registration.
///
/// The [`Drop`] impl is the ZTS retirement seam (issue #266): TSRM's
/// contract is that every thread that called `ts_resource()` frees its own
/// slot with `ts_free_thread()` **on itself** before the main thread runs
/// `php_module_shutdown()`. If a registered thread just dies (tokio
/// blocking-pool threads idle out after `keep_alive`, and all of them are
/// joined when the runtime is dropped), its `tsrm_tls_entry` lingers, and
/// module shutdown's `ts_free_id()` then walks the stale entry and runs the
/// per-thread globals dtors **on the shutting-down thread** — for pcre that
/// releases cached, request-lifetime `zend_string`s (named-subpattern
/// tables) into the wrong thread's Zend MM heap: `zend_mm_heap corrupted`
/// → SIGABRT. Running `ephpm_thread_shutdown()` from the TLS destructor
/// performs `php_request_shutdown()` + `ts_free_thread()` on the owning
/// thread, where every dtor frees into the heap that allocated it.
#[cfg(php_linked)]
struct ThreadPhpGuard {
    registered: std::cell::Cell<bool>,
}

#[cfg(php_linked)]
impl Drop for ThreadPhpGuard {
    fn drop(&mut self) {
        // Worker-mode threads retire explicitly via `worker_thread_shutdown()`
        // (the #258 seam), which clears the flag — this guard then no-ops, so
        // `ts_free_thread()` is never run twice for one thread.
        if !self.registered.get() {
            return;
        }
        self.registered.set(false);
        LIVE_PHP_THREADS.fetch_sub(1, Ordering::AcqRel);
        // If the PHP module is already gone (`PhpRuntime::shutdown()` ran
        // first), TSRM has been torn down and touching it would be UB. In
        // serve mode this cannot happen: the tokio runtime is dropped —
        // joining every blocking-pool thread, and running this guard —
        // before `PhpRuntime::shutdown()` is called.
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return;
        }
        // SAFETY: this thread is TSRM-registered (the flag was set) and is
        // exiting, so no further PHP executes on it. ephpm_thread_shutdown
        // runs php_request_shutdown (ending the lazily-kept-open final
        // request on the thread that owns it — its RSHUTDOWNs free
        // request-lifetime state, e.g. pcre subpattern-name strings, into
        // this thread's own Zend MM heap) and then ts_free_thread, which
        // destroys this thread's TSRM resources in reverse-id order on this
        // thread. No logging here: tracing's own TLS may already be gone.
        unsafe { ffi::ephpm_thread_shutdown() };
    }
}

#[cfg(php_linked)]
thread_local! {
    static THREAD_REGISTERED: ThreadPhpGuard =
        const { ThreadPhpGuard { registered: std::cell::Cell::new(false) } };
}

/// How many threads currently hold a TSRM registration made by
/// [`PhpRuntime::ensure_thread_registered`].
///
/// [`PhpRuntime::shutdown`] refuses to run `php_embed_shutdown()` while this is
/// non-zero. `php_module_shutdown()`'s `ts_free_id()` walks every live TSRM
/// entry **on the calling thread**, freeing another thread's request-lifetime
/// allocations into the wrong heap — `zend_mm_heap corrupted` → `SIGABRT`, the
/// #266 hazard. The normal shutdown sequence drives this to zero first (drop the
/// tokio runtime so blocking threads run their [`ThreadPhpGuard`]; drain the
/// worker/FPM pool so its threads call [`PhpRuntime::worker_thread_shutdown`]),
/// but an **early return** does not: a startup failure after the pool has
/// spawned — a failed `TcpListener::bind`, say — leaves pool threads registering
/// with TSRM while the main thread tears the module down underneath them. That
/// reproduces as a null-deref SIGSEGV in `zend_activate_modules` on an
/// `ephpm-fpm-N` thread. Skipping teardown at process exit costs nothing (the
/// kernel reclaims the memory); aborting costs the exit status and the log.
#[cfg(php_linked)]
static LIVE_PHP_THREADS: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

#[cfg(php_linked)]
thread_local! {
    /// Latched once this thread has contained a stack-overflow crash. Its Zend
    /// context is then poisoned — the recovery `siglongjmp`ed out mid-object-
    /// destruction, leaving the per-thread ZMM free lists and
    /// `EG(objects_store)` inconsistent — so the thread must never run PHP
    /// again and must never be torn down through `php_request_shutdown` /
    /// `ts_free_thread`.
    static THREAD_POISONED: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

/// Set once any thread in this process has contained a crash and abandoned its
/// TSRM entry.
///
/// [`PhpRuntime::shutdown`] reads it and skips `php_embed_shutdown()`: module
/// shutdown's `ts_free_id()` walks **every** remaining TSRM entry on the calling
/// thread, and an abandoned poisoned one is a guaranteed `zend_mm_heap
/// corrupted` → `SIGABRT` (this is issue #266's hazard, on entries we leaked on
/// purpose). Skipping is safe because the process is exiting: module shutdown
/// only frees memory the kernel reclaims anyway.
#[cfg(php_linked)]
static CONTEXT_POISONED: AtomicBool = AtomicBool::new(false);

/// Mark the current thread poisoned after a contained crash.
///
/// Latches the thread flag (so [`PhpRuntime::execute`] refuses further PHP on
/// this thread even if a caller ignores the error), disarms the
/// [`ThreadPhpGuard`] so thread exit does **not** run `ephpm_thread_shutdown()`
/// — its `php_request_shutdown` + `ts_free_thread` walk the poisoned heap and
/// would re-crash — and latches [`CONTEXT_POISONED`] so process teardown skips
/// module shutdown for the same reason. The poisoned per-thread Zend state is
/// deliberately leaked; abandoning it is the only safe option.
#[cfg(php_linked)]
fn mark_thread_poisoned() {
    THREAD_POISONED.with(|p| p.set(true));
    THREAD_REGISTERED.with(|g| {
        if g.registered.replace(false) {
            LIVE_PHP_THREADS.fetch_sub(1, Ordering::AcqRel);
        }
    });
    CONTEXT_POISONED.store(true, Ordering::Release);
}

/// Whether the current thread has contained a crash and must not run PHP.
#[cfg(php_linked)]
fn is_thread_poisoned() -> bool {
    THREAD_POISONED.with(std::cell::Cell::get)
}

#[derive(Debug, thiserror::Error)]
pub enum PhpError {
    /// PHP module initialization (`php_embed_init`) failed.
    #[error("PHP runtime failed to initialize")]
    InitFailed,

    /// A PHP script execution error (bailout, fatal, etc.).
    #[error("PHP script execution failed: {0}")]
    ExecutionFailed(String),

    /// The init/shutdown mutex was poisoned by a panic.
    #[error("PHP runtime lock poisoned")]
    LockPoisoned,

    /// `execute()` called before `init()`.
    #[error("PHP runtime not initialized")]
    NotInitialized,

    /// TSRM thread registration failed.
    #[error("PHP thread initialization failed")]
    ThreadInitFailed,

    /// The script was unwound by a `zend_bailout()` — out of memory, a
    /// resource limit, OPcache, or a C extension calling it directly.
    ///
    /// Distinct from every other variant because of what it says about the
    /// *output*: whatever the SAPI captured is a truncated prefix of a
    /// response the script never finished producing. It must never be
    /// completed as a success, so callers discard the partial body and answer
    /// 500 (`build_php_response`'s error arm) rather than returning it.
    ///
    /// PHP 8's `exit()`/`die()` is NOT a bailout — it throws an unwind-exit
    /// exception, which unwinds cleanly and yields a complete response.
    #[error("PHP script bailed out (truncated response discarded): {0}")]
    Bailout(String),

    /// A request overflowed the C stack — a deep object-graph free
    /// (`zend_object_std_dtor` ↔ `zend_objects_store_del` recursion) — and the
    /// crash guard contained it instead of the process aborting. Produced only
    /// when `[php] crash_containment` is active (see [`crate::crash_guard`]).
    ///
    /// Distinct from [`Self::Bailout`] in both cause and obligation: the fault
    /// was a hardware `SIGSEGV` recovered via `siglongjmp`, not a PHP-level
    /// bailout, and the thread that ran it is **poisoned**. The partial response
    /// is discarded and answered `500`, and the caller MUST retire that OS
    /// thread without running PHP teardown on it — which is what
    /// `ephpm-server`'s FPM pool does, and why containment is refused on tokio's
    /// shared blocking pool.
    #[error("PHP request contained after a C-stack overflow (thread retired): {0}")]
    Contained(String),
}

/// The `EPHPM_EXEC_*` return codes of `ephpm_execute_request` (defined in
/// `crates/ephpm-php/ephpm_wrapper.c` — keep the two in sync).
#[cfg(php_linked)]
mod exec_code {
    /// The script ran to completion.
    pub const OK: std::os::raw::c_int = 0;
    /// `php_request_startup()` failed (cold start only).
    pub const STARTUP_FAIL: std::os::raw::c_int = -1;
    /// The script chose to stop (`exit()`/`die()`); the response is complete.
    pub const SCRIPT_EXIT: std::os::raw::c_int = -2;
    /// A `zend_bailout()` unwound the script; the response is truncated.
    pub const BAILOUT: std::os::raw::c_int = -3;
    /// A `max_execution_time` timeout unwound the script. Like [`BAILOUT`] it
    /// forces a 500, but the captured response is a legitimate php-fpm-style
    /// error page and IS delivered rather than discarded.
    pub const TIMEOUT: std::os::raw::c_int = -4;
}

/// How a worker's framework loop ended (see [`PhpRuntime::run_worker`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkerExit {
    /// The loop ended cleanly: graceful drain or `worker_max_requests` recycle.
    Clean,
    /// The script ended while a request was still in flight (`exit()`/`die()`
    /// mid-request, or a break out of the loop). The C layer synthesized the
    /// response from SAPI state and delivered it; the worker must be recycled.
    ScriptExit,
    /// The in-flight request ended on a PHP fatal (uncaught `Throwable`,
    /// `E_ERROR`, …). Like [`WorkerExit::ScriptExit`] the C layer already
    /// synthesized and delivered the response — forced to 500 unless the
    /// script had set an explicit status — so the caller must NOT send another
    /// one; it differs only in that the worker died rather than chose to stop,
    /// which is what the recycle-reason metric reports.
    ScriptFatal,
    /// A `zend_bailout()` killed the worker. Nothing was delivered: unlike
    /// [`WorkerExit::ScriptFatal`], the C layer deliberately does **not**
    /// synthesize a response, because the capture buffers hold a truncated
    /// prefix of one the script never finished.
    ///
    /// The caller must recycle the worker and make sure the request cannot be
    /// mistaken for a success — fulfil a still-parked oneshot with a 500, and
    /// if a streaming response already put headers on the wire, abort the body
    /// stream instead of closing it cleanly
    /// ([`worker_bridge::clear_in_flight_streams`]).
    Fatal,
}

/// Wrapper around the PHP embed SAPI with ZTS (Zend Thread Safety).
///
/// PHP is built with `--enable-zts`, enabling TSRM (Thread Safe Resource
/// Manager). Each `spawn_blocking` thread registers with TSRM on first
/// use, getting its own copy of PHP global state. This allows concurrent
/// PHP execution across multiple threads.
///
/// The `Mutex` only protects `init()` / `shutdown()` (one-time lifecycle).
/// `execute()` runs lock-free on any registered thread.
pub struct PhpRuntime {
    initialized: bool,
}

/// Pre-scan `ephpm php` arguments for the ini flags that must be decided
/// *before* `php_embed_init()` runs: `-c <path>` (use this php.ini), `-n`
/// (load no ini at all), and every `-d name[=value]` directive. The C option
/// parser (`php_getopt`) only runs after init, which is too late to influence
/// which ini PHP loads — or which values MINIT-time consumers see: OPcache
/// decides at module startup whether it will ever activate
/// (`opcache.enable_cli`, the JIT knobs) and `extension=` lines load there
/// too, so `-d` has to reach `sapi_module.ini_entries` before startup exactly
/// as it does in php-cli (issue #331). This lightweight, `php_getopt`-aware
/// scan mirrors its short-option semantics (bundled flags,
/// attached-or-separate arguments) closely enough to locate them without ever
/// mistaking an option *argument* (e.g. the code after `-r`) for one of them.
///
/// Returns `(ini_path, no_ini, ini_defines)`. `-n` takes precedence over
/// `-c`, matching php-cli (but does not suppress `-d`, also matching).
/// Scanning stops at the first positional (the script), at `--`, or at the
/// `-` stdin sentinel — everything after those is script arguments, not
/// interpreter options.
#[cfg(any(php_linked, test))]
#[allow(clippy::too_many_lines)]
fn precscan_cli_ini_flags(args: &[String]) -> (Option<String>, bool, Vec<String>) {
    /// Short options that consume a following argument (from `cli_options`).
    const TAKES_ARG: &[char] = &['B', 'c', 'd', 'E', 'F', 'f', 'R', 'r', 'S', 't'];

    let mut ini_path: Option<String> = None;
    let mut no_ini = false;
    let mut ini_defines: Vec<String> = Vec::new();
    let mut i = 0;
    while i < args.len() {
        let arg = &args[i];
        // `--` ends options; `-` is the stdin positional. Either way, stop.
        if arg == "--" || arg == "-" {
            break;
        }
        if let Some(long) = arg.strip_prefix("--") {
            // Long options (`--rf name`, `--ini`, …) never affect ini loading,
            // but the reflection ones take a separate argument that must be
            // skipped so it is not re-read as an option.
            let name = long.split('=').next().unwrap_or("");
            let long_takes_arg = matches!(
                name,
                "rf" | "rfunction"
                    | "rc"
                    | "rclass"
                    | "re"
                    | "rextension"
                    | "rz"
                    | "rzendextension"
                    | "ri"
                    | "rextinfo"
            );
            if long_takes_arg && !long.contains('=') {
                i += 1; // skip its argument
            }
            i += 1;
            continue;
        }
        if let Some(shorts) = arg.strip_prefix('-') {
            let chars: Vec<char> = shorts.chars().collect();
            let mut j = 0;
            let mut consumed_next = false;
            while j < chars.len() {
                let ch = chars[j];
                if ch == 'n' {
                    no_ini = true;
                    j += 1;
                    continue;
                }
                if ch == 'c' {
                    // Rest of this token is the value (`-c/path`), else the next
                    // token (`-c /path`). Match php_getopt: no `=` stripping.
                    let rest: String = chars[j + 1..].iter().collect();
                    if rest.is_empty() {
                        if let Some(next) = args.get(i + 1) {
                            ini_path = Some(next.clone());
                            consumed_next = true;
                        }
                    } else {
                        ini_path = Some(rest);
                    }
                    break;
                }
                if ch == 'd' {
                    // Same value shapes as `-c`: attached (`-dfoo=1`) or the
                    // next token (`-d foo=1`). Order is preserved — a later
                    // `-d` for the same key wins, as in php-cli.
                    let rest: String = chars[j + 1..].iter().collect();
                    if rest.is_empty() {
                        if let Some(next) = args.get(i + 1) {
                            ini_defines.push(next.clone());
                            consumed_next = true;
                        }
                    } else {
                        ini_defines.push(rest);
                    }
                    break;
                }
                if TAKES_ARG.contains(&ch) {
                    // Some other arg-taking option (r, f, d, …). Its argument is
                    // the rest of this token, or the next token — skip it so its
                    // content is never scanned as an option.
                    if chars[j + 1..].is_empty() {
                        consumed_next = true;
                    }
                    break;
                }
                j += 1; // no-arg flag (a, e, l, m, q, s, w, v, C, H, i, h, ?)
            }
            if consumed_next {
                i += 1;
            }
            i += 1;
            continue;
        }
        // A bare positional (the script name): options are done.
        break;
    }
    // `-n` (ignore all ini) subsumes `-c` (choose an ini), matching php-cli.
    // `-d` directives survive `-n` — `php -n -d x=y` applies them there too.
    (if no_ini { None } else { ini_path }, no_ini, ini_defines)
}

/// Whether the PHP module has been initialized (set once by `init()`).
///
/// Checked by `execute()` without acquiring the mutex — the atomic
/// provides a fast-path "is PHP ready?" check.
static PHP_INITIALIZED: AtomicBool = AtomicBool::new(false);

/// Mutex protecting one-time `init()` / `shutdown()` lifecycle.
///
/// Not held during `execute()` — ZTS threads execute concurrently.
static PHP_RUNTIME: Mutex<Option<PhpRuntime>> = Mutex::new(None);

impl PhpRuntime {
    /// Initialize the PHP runtime.
    ///
    /// This must be called once before any PHP requests can be executed.
    /// When libphp is linked, calls `php_embed_init()` to set up the
    /// interpreter and installs our custom SAPI callbacks.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` if the runtime mutex is poisoned,
    /// or `PhpError::InitFailed` if PHP initialization fails.
    pub fn init() -> Result<(), PhpError> {
        Self::init_with_ini_file(None)
    }

    /// Initialize the PHP runtime with a custom ini file.
    ///
    /// If `ini_file` is `Some`, that file will be loaded before any PHP
    /// scripts execute. If `None`, PHP uses its default ini file search.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` if the runtime mutex is poisoned,
    /// or `PhpError::InitFailed` if PHP initialization fails.
    pub fn init_with_ini_file(_ini_file: Option<&std::path::Path>) -> Result<(), PhpError> {
        let mut runtime = PHP_RUNTIME.lock().map_err(|_| PhpError::LockPoisoned)?;
        if runtime.is_some() {
            return Ok(()); // Already initialized
        }

        #[cfg(php_linked)]
        {
            use std::ffi::CString;

            // Install our embed module-startup shim so KV functions land in
            // GLOBAL_FUNCTION_TABLE before any tokio worker thread copies it.
            // Safety: must run before php_embed_init() so the shim is installed
            // when embed's startup callback is invoked. No PHP state exists yet.
            unsafe { ffi::ephpm_pre_init() };

            // Keep the CString alive until php_embed_init() completes so the
            // pointer remains valid while PHP reads the configuration.
            let _ini_file_cstring = if let Some(path) = _ini_file {
                let cstr = CString::new(path.to_string_lossy().into_owned())
                    .unwrap_or_else(|_| CString::new("").unwrap());
                // Safety: Must be called before php_embed_init() so the ini file
                // is loaded during module startup. The pointer is valid until
                // php_embed_init() returns.
                unsafe { ffi::ephpm_set_ini_file(cstr.as_ptr()) };
                Some(cstr)
            } else {
                None
            };

            // Initialize PHP embed SAPI (module + initial request startup).
            // Safety: php_embed_init must be called exactly once before any PHP
            // execution. We guarantee this via the Mutex + Option guard.
            let arg0 = CString::new("ephpm").unwrap();
            let mut argv_ptrs = [arg0.as_ptr().cast_mut(), std::ptr::null_mut()];
            // Safety: argv is valid, argc matches the number of non-null entries.
            let ret = unsafe { ffi::php_embed_init(1, argv_ptrs.as_mut_ptr()) };
            if ret != 0 {
                return Err(PhpError::InitFailed);
            }

            // Install our custom SAPI callbacks (ub_write, read_post, etc.)
            // Safety: Must be called after php_embed_init, before any requests.
            unsafe { ffi::ephpm_install_sapi() };

            // Apply INI settings (disable stack size checking for tokio threads)
            // Safety: Must be called after php_embed_init.
            unsafe { ffi::ephpm_apply_ini_settings() };

            tracing::info!("PHP runtime initialized (libphp linked)");
        }

        #[cfg(not(php_linked))]
        {
            tracing::info!("PHP runtime initialized (stub — no libphp linked)");
        }

        *runtime = Some(PhpRuntime { initialized: true });
        PHP_INITIALIZED.store(true, Ordering::Release);
        Ok(())
    }

    /// Shut down the PHP runtime.
    ///
    /// Calls `php_embed_shutdown()` and cleans up.
    ///
    /// Mirror of the single-threaded-phase discipline `init()` documents:
    /// just as `init()` must run before any worker thread exists, this must
    /// run **after every PHP-registered thread has exited** (fpm mode: drop
    /// the tokio runtime first so its blocking pool joins; worker mode:
    /// wait for the pool to drain). Each exiting thread retires its own
    /// TSRM slot via [`ThreadPhpGuard`]; if a registered thread is still
    /// alive here, `php_module_shutdown()`'s `ts_free_id()` walks that
    /// thread's live TSRM entry and frees its per-thread state on *this*
    /// thread — cross-heap `efree` → `zend_mm_heap corrupted` (issue #266).
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` if the runtime mutex is poisoned.
    pub fn shutdown() -> Result<(), PhpError> {
        let mut runtime = PHP_RUNTIME.lock().map_err(|_| PhpError::LockPoisoned)?;
        if let Some(rt) = runtime.take() {
            PHP_INITIALIZED.store(false, Ordering::Release);
            drop(rt);

            #[cfg(php_linked)]
            {
                let live_threads = LIVE_PHP_THREADS.load(Ordering::Acquire);
                if CONTEXT_POISONED.load(Ordering::Acquire) {
                    // At least one thread contained a crash and abandoned its
                    // TSRM entry (see `mark_thread_poisoned`). `ts_free_id()`
                    // inside php_module_shutdown walks EVERY remaining entry on
                    // this thread and would free the poisoned thread's
                    // request-lifetime allocations out of a corrupt heap —
                    // `zend_mm_heap corrupted` → SIGABRT, i.e. a clean SIGTERM
                    // would exit 134 instead of 0. The process is on its way
                    // out and module shutdown only frees memory the kernel
                    // reclaims regardless, so skipping it is strictly better
                    // than aborting.
                    tracing::warn!(
                        "skipping PHP module shutdown — a crash was contained during this \
                         process's lifetime and its thread context was abandoned; walking \
                         that TSRM entry would abort. Process memory is reclaimed by the OS."
                    );
                } else if live_threads > 0 {
                    // A PHP-registered thread is still alive — the caller
                    // returned early (a startup failure after the pool spawned,
                    // typically) without draining it. `ts_free_id()` would free
                    // that thread's request-lifetime state on THIS thread, and
                    // the thread itself may still be inside php_request_startup.
                    // Skip rather than race it. See LIVE_PHP_THREADS.
                    tracing::warn!(
                        live_threads,
                        "skipping PHP module shutdown — PHP-registered threads are still \
                         live, so tearing the module down now would free their per-thread \
                         state on the wrong thread. Process memory is reclaimed by the OS."
                    );
                } else {
                    // Safety: Paired with php_embed_init in init().
                    // Handles request shutdown + module shutdown.
                    unsafe { ffi::php_embed_shutdown() };
                    tracing::info!("PHP runtime shut down");
                }
            }

            #[cfg(not(php_linked))]
            {
                tracing::info!("PHP runtime shut down (stub)");
            }
        }
        Ok(())
    }

    /// Finalize initialization for HTTP serve mode.
    ///
    /// `php_embed_init()` starts a request automatically. This marks it as
    /// active so that the first call to `ephpm_execute_request()` properly
    /// shuts it down before starting its own request lifecycle.
    ///
    /// Must be called after [`init()`] and before the first HTTP request.
    /// Do NOT call this before using CLI mode (`cli_main`), which reuses
    /// the embed's initial request.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` if the runtime mutex is poisoned,
    /// or `PhpError::NotInitialized` if the runtime hasn't been initialized.
    pub fn finalize_for_http() -> Result<(), PhpError> {
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return Err(PhpError::NotInitialized);
        }

        #[cfg(php_linked)]
        {
            // Safety: Called once after init, marks the embed's initial request
            // as active so ephpm_execute_request shuts it down on first call.
            unsafe { ffi::ephpm_finalize_init() };
            tracing::debug!("PHP embed initial request marked active (ready for HTTP)");
        }

        Ok(())
    }

    /// Record the configured `max_execution_time` (seconds) that the request
    /// paths use to arm PHP's per-thread execution timer.
    ///
    /// The embed SAPI resets the `max_execution_time` ini entry to `0`
    /// (unlimited) at runtime, so the generated-ini value cannot be relied on to
    /// arm the timer; ePHPm arms it explicitly per request from this value
    /// instead. On builds without per-thread timers, and in stub mode, this is a
    /// no-op. Call once after [`PhpRuntime::init`].
    pub fn set_max_execution_time(secs: u32) {
        #[cfg(php_linked)]
        {
            // `c_long` is 64-bit on LP64 (Linux, macOS) but 32-bit on Windows
            // (LLP64), so `u32` has no infallible conversion on every target —
            // `i32: From<u32>` does not exist. Saturate instead: a configured
            // limit above `c_long::MAX` seconds is ~68 years at 32-bit, which
            // is indistinguishable from "no limit" for a request timeout.
            let secs =
                ::std::os::raw::c_long::try_from(secs).unwrap_or(::std::os::raw::c_long::MAX);
            // SAFETY: ephpm_set_max_execution_time only stores the value into a
            // C static; it touches no PHP runtime state and is safe to call from
            // the single-threaded startup path before the tokio runtime exists.
            unsafe { ffi::ephpm_set_max_execution_time(secs) };
        }
        #[cfg(not(php_linked))]
        {
            let _ = secs;
        }
    }

    /// Check whether the PHP runtime is initialized and ready.
    ///
    /// Used by health/readiness probes to determine if the server can
    /// accept PHP requests. In stub mode (no `php_linked`), always
    /// returns `false`.
    #[must_use]
    pub fn is_ready() -> bool {
        PHP_INITIALIZED.load(Ordering::Acquire)
    }

    // ── CLI mode methods ──────────────────────────────────────────────────

    /// Get the embedded PHP version string (e.g. "8.5.4").
    ///
    /// This reads a compile-time constant and does not require the PHP
    /// runtime to be initialized.
    #[cfg(php_linked)]
    #[must_use]
    pub fn php_version() -> &'static str {
        // Safety: ephpm_get_php_version returns a pointer to the static
        // PHP_VERSION string constant, which is valid for the entire process.
        let ptr = unsafe { ffi::ephpm_get_php_version() };
        // Safety: PHP_VERSION is a valid UTF-8 C string literal.
        unsafe { std::ffi::CStr::from_ptr(ptr) }.to_str().unwrap_or("unknown")
    }

    /// Get the embedded PHP version string (stub mode).
    #[cfg(not(php_linked))]
    #[must_use]
    pub fn php_version() -> &'static str {
        "not available (stub mode — no libphp linked)"
    }

    /// Run the PHP CLI with the given arguments.
    ///
    /// Passes `args` through to PHP's argument parser, supporting all
    /// standard PHP CLI flags (`-v`, `-r`, `-f`, `-m`, `-i`, `-l`, etc.).
    /// Output goes directly to stdout/stderr.
    ///
    /// Initializes the PHP runtime if needed. Returns the PHP exit code
    /// (0 for success).
    ///
    /// # Errors
    ///
    /// Returns `PhpError::LockPoisoned` or `PhpError::InitFailed` on failure.
    pub fn cli_main(args: &[String]) -> Result<i32, PhpError> {
        // Init-time CLI decisions that must be settled BEFORE php_embed_init()
        // runs (inside `Self::init()`): the SAPI identity ("cli"), which
        // php.ini to load (`-c <path>` / `-n`), and the `-d` ini directives —
        // those must be in `sapi_module.ini_entries` when module startup runs
        // so MINIT-time consumers (OPcache/JIT activation, `extension=`) see
        // them, exactly as php-cli applies them (issue #331). Parsed from a
        // lightweight, php_getopt-aware pre-scan because the C option parser
        // only runs afterwards. The `-c` path CString is bound for the rest of
        // this function so its pointer stays valid until init completes.
        #[cfg(php_linked)]
        let _cli_ini_path_cstring = {
            use std::ffi::CString;

            // SAFETY: called on the single-threaded CLI startup path before
            // php_embed_init(). Sets a process global read during module
            // startup; no PHP runtime state exists yet.
            unsafe { ffi::ephpm_enable_cli_mode() };

            let (ini_override, no_ini, ini_defines) = precscan_cli_ini_flags(args);

            for define in &ini_defines {
                // A `-d` value containing a NUL cannot be a valid ini
                // directive; skip it rather than truncate it silently.
                if let Ok(cstr) = CString::new(define.as_str()) {
                    // SAFETY: before-init timing contract as above. The C side
                    // copies the string immediately, so the CString may drop
                    // at the end of this iteration.
                    unsafe { ffi::ephpm_cli_add_ini_define(cstr.as_ptr()) };
                }
            }

            if no_ini {
                // SAFETY: same before-init timing contract.
                unsafe { ffi::ephpm_cli_set_no_ini() };
                None
            } else if let Some(path) = ini_override {
                let cstr = CString::new(path).unwrap_or_else(|_| CString::new("").unwrap());
                // SAFETY: the pointer must remain valid until php_embed_init()
                // completes; the CString is bound below for the whole function.
                unsafe { ffi::ephpm_set_ini_file(cstr.as_ptr()) };
                Some(cstr)
            } else {
                None
            }
        };

        Self::init()?;

        #[cfg(php_linked)]
        {
            use std::ffi::CString;

            // CLI mode uses the initial embed request context on the main thread.
            // Acquire the mutex to prevent concurrent CLI + HTTP mode.
            let _runtime = PHP_RUNTIME.lock().map_err(|_| PhpError::LockPoisoned)?;

            // Build argc/argv for the C function.
            // argv[0] is the program name, followed by the user's args.
            let mut c_args: Vec<CString> = Vec::with_capacity(args.len() + 1);
            c_args.push(CString::new("ephpm").unwrap());
            for arg in args {
                c_args
                    .push(CString::new(arg.as_str()).map_err(|e| {
                        PhpError::ExecutionFailed(format!("invalid argument: {e}"))
                    })?);
            }

            let mut argv_ptrs: Vec<*mut std::os::raw::c_char> =
                c_args.iter().map(|s| s.as_ptr().cast_mut()).collect();
            argv_ptrs.push(std::ptr::null_mut());

            let argc = c_args.len() as std::os::raw::c_int;

            // Safety: We hold the runtime lock. argv_ptrs is valid for argc
            // entries plus a null terminator. The C function handles request
            // lifecycle and bailout protection internally.
            let ret = unsafe { ffi::ephpm_cli_main(argc, argv_ptrs.as_mut_ptr()) };
            Ok(ret)
        }

        #[cfg(not(php_linked))]
        {
            let _ = args;
            Err(PhpError::ExecutionFailed(
                "PHP not linked — build with PHP_SDK_PATH to enable CLI mode".into(),
            ))
        }
    }

    // ── HTTP mode methods ────────────────────────────────────────────────

    /// Execute a PHP request.
    ///
    /// With ZTS, this runs **without** the global mutex — each
    /// `spawn_blocking` thread has its own TSRM-registered PHP context.
    /// On first call from a new thread, the thread is automatically
    /// registered with TSRM via `ephpm_thread_init()`.
    ///
    /// This function is designed to be called from `tokio::task::spawn_blocking`
    /// since it blocks the calling thread for the duration of PHP execution.
    ///
    /// # Errors
    ///
    /// Returns `PhpError::NotInitialized` if the runtime hasn't been
    /// initialized, or `PhpError::ThreadInitFailed` if TSRM registration fails.
    #[allow(clippy::needless_pass_by_value)]
    pub fn execute(request: PhpRequest) -> Result<PhpResponse, PhpError> {
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return Err(PhpError::NotInitialized);
        }

        // Belt-and-braces: a thread that contained a prior crash has a poisoned
        // Zend context and must never run PHP again. The FPM pool retires such a
        // thread the moment it sees `Contained`, so in the supported
        // configuration this never fires — it exists so a caller that ignores
        // the error cannot turn a contained crash into an uncontained one.
        // Checked before TSRM is touched.
        #[cfg(php_linked)]
        if is_thread_poisoned() {
            return Err(PhpError::Contained("thread retired after a prior contained crash".into()));
        }

        #[cfg(php_linked)]
        Self::ensure_thread_registered()?;

        tracing::debug!(
            method = %request.method,
            uri = %request.uri,
            script = %request.script_filename.display(),
            "executing PHP request"
        );

        #[cfg(php_linked)]
        {
            let result = Self::execute_php(&request);
            // Per-request DB-bridge teardown (fpm-mode seam). This is the
            // single choke point every fpm-style request passes through on
            // the same spawn_blocking thread that ran the script, whatever
            // the outcome (OK, exit(), bailout, startup failure) — so a
            // transaction the script left open is rolled back before this
            // thread can serve an unrelated request, and the staged
            // result/error memory is released instead of sitting until the
            // thread's next request. Pure Rust + litewire — no Zend calls,
            // so no zend_try guard is needed.
            db_bridge::on_request_end();
            result
        }

        #[cfg(not(php_linked))]
        {
            // Stub response for development without libphp
            Ok(PhpResponse {
                status: 200,
                headers: vec![("Content-Type".to_string(), "text/html".to_string())],
                body: format!(
                    "<html><body>\
                     <h1>ePHPm Stub</h1>\
                     <p>PHP not linked. Would execute: {}</p>\
                     <p>Build with <code>PHP_SDK_PATH</code> set to enable PHP execution.</p>\
                     </body></html>",
                    request.script_filename.display()
                )
                .into_bytes(),
            })
        }
    }

    /// Ensure the current thread is registered with TSRM.
    ///
    /// Called on every `execute()` — fast-path is a thread-local check.
    /// Only the first call on each thread actually registers with TSRM.
    #[cfg(php_linked)]
    fn ensure_thread_registered() -> Result<(), PhpError> {
        THREAD_REGISTERED.with(|guard| {
            if guard.registered.get() {
                return Ok(());
            }

            // SAFETY: PHP module has been initialized (checked via atomic above).
            // ephpm_thread_init() calls ts_resource(0) + php_request_startup(),
            // which are the correct TSRM registration sequence. The C function
            // uses zend_try/zend_catch internally for bailout protection.
            let ret = unsafe { ffi::ephpm_thread_init() };
            if ret != 0 {
                return Err(PhpError::ThreadInitFailed);
            }

            // Setting the flag arms the guard's Drop: when this thread exits
            // (idle timeout or runtime shutdown), it retires its own TSRM
            // slot instead of leaving a stale entry for module shutdown to
            // trip over (issue #266). The counter is the process-wide view of
            // the same fact, so `shutdown()` can refuse to tear the module down
            // while any registration is still outstanding.
            guard.registered.set(true);
            LIVE_PHP_THREADS.fetch_add(1, Ordering::AcqRel);
            tracing::debug!("TSRM thread registered for PHP execution");
            Ok(())
        })
    }

    /// Execute a PHP script via our custom SAPI bridge.
    ///
    /// Sets up per-request state in C, executes the script with proper
    /// request lifecycle management, and captures the response.
    #[cfg(php_linked)]
    fn execute_php(request: &PhpRequest) -> Result<PhpResponse, PhpError> {
        use std::ffi::CString;

        // Clear previous request state in the C wrapper's thread-local buffers.
        // SAFETY: The current thread is registered with TSRM and owns its
        // thread-local C state. No concurrent access to these buffers.
        unsafe { ffi::ephpm_request_clear() };

        // Prepare C strings for the request info.
        // These must stay alive until ephpm_execute_request returns.
        let method = CString::new(request.method.as_str())
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid method: {e}")))?;
        let uri = CString::new(request.uri.as_str())
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid URI: {e}")))?;
        let query_string = CString::new(request.query_string.as_str())
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid query string: {e}")))?;
        let content_type_str = request.content_type.as_deref().unwrap_or("");
        let content_type = CString::new(content_type_str)
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid content type: {e}")))?;
        let cookie = CString::new(request.cookie_string())
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid cookie: {e}")))?;
        let script_path = request
            .script_filename
            .to_str()
            .ok_or_else(|| PhpError::ExecutionFailed("non-UTF8 script path".into()))?;
        let script_filename = CString::new(script_path)
            .map_err(|e| PhpError::ExecutionFailed(format!("invalid script path: {e}")))?;

        // Pass POST body — use null pointer for empty bodies
        let post_data_ptr =
            if request.body.is_empty() { std::ptr::null() } else { request.body.as_ptr().cast() };

        // Set core request info in C
        // Safety: All CString pointers are valid and will stay alive.
        unsafe {
            ffi::ephpm_request_set_info(
                method.as_ptr(),
                uri.as_ptr(),
                query_string.as_ptr(),
                content_type.as_ptr(),
                cookie.as_ptr(),
                post_data_ptr,
                request.body.len(),
                script_filename.as_ptr(),
            );
        }

        // Build and pass server variables ($_SERVER)
        let server_vars = request.server_variables();
        let c_server_vars: Vec<(CString, CString)> = server_vars
            .iter()
            .filter_map(|(k, v)| {
                Some((CString::new(k.as_str()).ok()?, CString::new(v.as_str()).ok()?))
            })
            .collect();

        for (key, value) in &c_server_vars {
            // Safety: CString pointers are valid and stay alive.
            unsafe {
                ffi::ephpm_request_add_server_var(key.as_ptr(), value.as_ptr());
            }
        }

        // Execute the PHP request on this thread's TSRM context.
        //
        // Two shapes, selected by the `[php] crash_containment` master switch:
        //
        // - OFF (default): the bare FFI call, byte-identical to every release
        //   before containment existed. A C-stack overflow aborts the process
        //   via the fatal-signal handler, as it always has.
        // - ON: the same call inside the per-thread `sigsetjmp` recovery region.
        //   The region wraps the WHOLE call deliberately, because the deep free
        //   that overflows the stack can happen in three places inside it — the
        //   script's own `$graph = null`, the LAZY `php_request_shutdown` of the
        //   *previous* request at the top of `ephpm_execute_request`, or a
        //   registered shutdown function.
        //
        // Nothing is allocated inside the guarded closure: on containment the
        // `siglongjmp` skips every Rust destructor between here and the recovery
        // point, so the closure body is exactly one FFI call and the CStrings /
        // Vec above (created OUTSIDE it) still drop normally afterwards.
        let ret = if crash_guard::enabled() {
            let filename_ptr = script_filename.as_ptr();
            let mut ret: std::os::raw::c_int = exec_code::BAILOUT;
            let guarded = crash_guard::run_guarded(|| {
                // SAFETY: This thread is registered with TSRM. All PHP globals
                // accessed by ephpm_execute_request are thread-local under ZTS.
                // The C function uses setjmp/longjmp bailout protection for
                // PHP-level bailouts; a hardware stack-overflow SIGSEGV escapes
                // that and is caught by the crash guard's signal-handler
                // recovery instead. `script_filename` outlives the call.
                ret = unsafe { ffi::ephpm_execute_request(filename_ptr) };
            });

            if guarded == crash_guard::Guarded::Contained {
                // The recovery jumped out mid-object-destruction: this thread's
                // ZMM free lists and EG(objects_store) are inconsistent. The
                // damage is confined to THIS thread, but it must never run PHP
                // again nor be torn down through php_request_shutdown /
                // ts_free_thread (both walk the poisoned heap and would
                // re-crash). mark_thread_poisoned() latches the refusal,
                // disarms the TLS retirement guard, and makes process teardown
                // skip module shutdown; the poisoned Zend context is
                // deliberately leaked. Retiring the OS thread is the caller's
                // job — see PhpError::Contained.
                mark_thread_poisoned();
                tracing::error!(
                    script = %request.script_filename.display(),
                    method = %request.method,
                    uri = %request.uri,
                    "PHP request overflowed the C stack (deep object-graph free) — \
                     contained on this thread, returning 500; the thread is poisoned \
                     and must be retired"
                );
                return Err(PhpError::Contained(format!(
                    "{} ({} {})",
                    request.script_filename.display(),
                    request.method,
                    request.uri
                )));
            }
            ret
        } else {
            // SAFETY: This thread is registered with TSRM. All PHP globals
            // accessed by ephpm_execute_request are thread-local under ZTS.
            // The C function uses setjmp/longjmp bailout protection.
            unsafe { ffi::ephpm_execute_request(script_filename.as_ptr()) }
        };

        // Retrieve the captured response from C
        let body = {
            let mut len: usize = 0;
            // Safety: out_len pointer is valid.
            let ptr = unsafe { ffi::ephpm_get_output_buf(&mut len) };
            if ptr.is_null() || len == 0 {
                Vec::new()
            } else {
                // Safety: ptr is valid for len bytes (managed by C output buffer).
                unsafe { std::slice::from_raw_parts(ptr.cast::<u8>(), len) }.to_vec()
            }
        };

        // Safety: No arguments, returns a simple int.
        let status_code = unsafe { ffi::ephpm_get_response_code() };

        let headers = {
            let mut len: usize = 0;
            // Safety: out_len pointer is valid.
            let ptr = unsafe { ffi::ephpm_get_response_headers(&mut len) };
            if ptr.is_null() || len == 0 {
                Vec::new()
            } else {
                // Safety: ptr is valid for len bytes (managed by C headers buffer).
                let raw = unsafe { std::slice::from_raw_parts(ptr.cast::<u8>(), len) };
                // Headers are "Name: Value\n" lines. Parse them.
                String::from_utf8_lossy(raw)
                    .lines()
                    .filter_map(|line| {
                        let (name, value) = line.split_once(": ")?;
                        Some((name.to_string(), value.to_string()))
                    })
                    .collect()
            }
        };

        let status = u16::try_from(status_code).unwrap_or(200);

        match ret {
            exec_code::OK => Ok(PhpResponse { status, headers, body }),
            exec_code::STARTUP_FAIL => {
                Err(PhpError::ExecutionFailed("php_request_startup failed".into()))
            }
            // A max_execution_time timeout. PHP's own timer fired, raised the
            // catchable "Maximum execution time exceeded" fatal, ran shutdown
            // functions and flushed buffers — the captured body is a complete
            // php-fpm-style 500 page (status is already 500 from the C layer),
            // so it is delivered rather than discarded like a memory bailout.
            exec_code::TIMEOUT => {
                tracing::warn!(
                    script = %request.script_filename.display(),
                    method = %request.method,
                    uri = %request.uri,
                    "PHP script exceeded max_execution_time — returning the PHP \
                     fatal as a 500 (shutdown functions ran, output flushed)"
                );
                Ok(PhpResponse { status, headers, body })
            }
            // A zend_bailout() unwound the script. `body` is a truncated
            // prefix of a response that was never finished, so it is dropped
            // here rather than shipped: completing it would hand a caching
            // proxy, a health probe, or a client half a document labelled as
            // success. The fpm path buffers the whole response before this
            // point, so nothing has reached the wire yet and answering 500 is
            // always possible.
            //
            // This is the only place the failure is visible at all — the
            // engine prints nothing for a bare zend_bailout().
            exec_code::BAILOUT => {
                tracing::error!(
                    script = %request.script_filename.display(),
                    method = %request.method,
                    uri = %request.uri,
                    discarded_body_bytes = body.len(),
                    output_tail = %truncated_output_tail(&body),
                    "PHP script terminated in a Zend bailout (out of memory, a \
                     resource limit, or an extension calling zend_bailout()) — \
                     truncated response discarded, returning 500"
                );
                Err(PhpError::Bailout(format!(
                    "{} ({} {})",
                    request.script_filename.display(),
                    request.method,
                    request.uri
                )))
            }
            // exit()/die() unwinds cleanly, so the captured response is
            // complete and is returned as-is, keeping whatever status the
            // script chose (an empty one is still an error — nothing was
            // produced).
            exec_code::SCRIPT_EXIT => {
                if body.is_empty() {
                    Err(PhpError::ExecutionFailed("PHP exited without output".into()))
                } else {
                    Ok(PhpResponse { status, headers, body })
                }
            }
            other => Err(PhpError::ExecutionFailed(format!(
                "ephpm_execute_request returned an unknown code {other}"
            ))),
        }
    }

    /// Register the KV store so PHP native `ephpm_kv_*` functions can
    /// access it.
    ///
    /// Must be called after [`init()`] (so the PHP runtime exists) and
    /// before any PHP requests execute. Typically called from
    /// `ephpm-server` after creating the [`ephpm_kv::store::Store`].
    ///
    /// In stub mode (no `php_linked`), this is a no-op.
    pub fn set_kv_store(store: &std::sync::Arc<ephpm_kv::store::Store>) {
        #[cfg(php_linked)]
        {
            kv_bridge::set_store(std::sync::Arc::clone(store));

            // Safety: KV_OPS is a static with stable address. ephpm_set_kv_ops
            // copies the struct into the C global — the pointer only needs to be
            // valid for the duration of this call.
            unsafe { ffi::ephpm_set_kv_ops(&kv_bridge::KV_OPS) };

            tracing::info!("KV store wired to PHP native functions");
        }

        #[cfg(not(php_linked))]
        {
            let _ = store;
            tracing::debug!("KV store set_kv_store no-op (stub mode)");
        }
    }

    /// Register the litewire backend that backs the PHP native
    /// `ephpm_db_*` functions (`ephpm_db_query`, `ephpm_db_execute`).
    ///
    /// `backend` must be the **same** erased instance the wire frontends
    /// serve — including ephpm-server's `TrackedBackend` wrapper — so
    /// bridge queries land in query-stats exactly like wire queries.
    /// `handle` is the server's tokio runtime handle, pinned so the sync
    /// FFI callbacks can `block_on` session work (see the async-boundary
    /// note in [`db_bridge`]).
    ///
    /// Call only when a `[db.sqlite]` backend is active; when never
    /// called, the PHP functions throw a clean exception instead of
    /// executing. First registration wins (mirrors [`Self::set_kv_store`]).
    ///
    /// In stub mode (no `php_linked`) the Rust-side registration still
    /// happens (it is used by stub tests) but no PHP wiring occurs.
    pub fn set_db_backend(
        backend: litewire::backend::SharedBackend,
        handle: tokio::runtime::Handle,
    ) {
        let registered = db_bridge::set_backend(backend, handle);

        #[cfg(php_linked)]
        if registered {
            // Safety: DB_OPS is a static with a stable address.
            // ephpm_set_db_ops copies the struct into the C global — the
            // pointer only needs to be valid for the duration of this call.
            unsafe { ffi::ephpm_set_db_ops(&db_bridge::DB_OPS) };

            tracing::info!("db backend wired to PHP native functions");
        }

        #[cfg(not(php_linked))]
        if registered {
            tracing::debug!("db backend registered (stub mode, no PHP wiring)");
        }
    }

    /// Register a **per-site** backend resolver for the PHP native
    /// `ephpm_db_*` functions (multi-site secure-multi-tenancy mode).
    ///
    /// Unlike [`Self::set_db_backend`] (one global backend), this hands the
    /// bridge a [`db_bridge::SiteBackendResolver`] (ephpm-server's per-site
    /// registry). Each request's query is routed to its own tenant's database
    /// based on the site key set by the router via
    /// [`db_bridge::set_current_site`] before PHP runs. Mutually exclusive with
    /// `set_db_backend` — first registration wins.
    ///
    /// In stub mode (no `php_linked`) the Rust-side registration still happens
    /// but no PHP wiring occurs.
    pub fn set_db_backend_resolver(
        resolver: std::sync::Arc<dyn db_bridge::SiteBackendResolver>,
        handle: tokio::runtime::Handle,
    ) {
        let registered = db_bridge::set_resolver(resolver, handle);

        #[cfg(php_linked)]
        if registered {
            // Safety: DB_OPS is a static with a stable address.
            // ephpm_set_db_ops copies the struct into the C global — the
            // pointer only needs to be valid for the duration of this call.
            unsafe { ffi::ephpm_set_db_ops(&db_bridge::DB_OPS) };

            tracing::info!("per-site db resolver wired to PHP native functions");
        }

        #[cfg(not(php_linked))]
        if registered {
            tracing::debug!("per-site db resolver registered (stub mode, no PHP wiring)");
        }
    }

    /// Register the WebSocket connection registry backing the PHP native
    /// `ephpm_ws_*` functions.
    ///
    /// Call only when `[server.websocket] enabled = true`. When never called,
    /// the functions still **exist** (so `function_exists()` and a portable
    /// script both behave) but every call reports failure rather than reaching
    /// a socket.
    ///
    /// Must be called after [`init()`] and before any PHP request executes.
    /// First registration wins, mirroring [`Self::set_kv_store`].
    ///
    /// In stub mode (no `php_linked`) the Rust-side registration still happens
    /// (stub tests use it) but no PHP wiring occurs.
    pub fn set_ws_registry(registry: std::sync::Arc<ephpm_ws::Registry>) {
        let registered = ws_bridge::set_registry(registry);

        #[cfg(php_linked)]
        if registered {
            // Safety: WS_OPS is a static with a stable address.
            // ephpm_set_ws_ops copies the struct into the C global — the
            // pointer only needs to be valid for the duration of this call.
            unsafe { ffi::ephpm_set_ws_ops(&ws_bridge::WS_OPS) };

            tracing::info!("websocket registry wired to PHP native functions");
        }

        #[cfg(not(php_linked))]
        if registered {
            tracing::debug!("websocket registry registered (stub mode, no PHP wiring)");
        }
    }

    // ── Worker mode ───────────────────────────────────────────────────────

    /// Install the worker-mode ops table so `\Ephpm\Worker\take_request()` /
    /// `send_response()` call into the Rust dispatch bridge.
    ///
    /// Must be called after [`init()`] and before any worker boots. Also sets
    /// whether native superglobals are populated per request
    /// (`worker.populate_superglobals`).
    ///
    /// In stub mode this is a no-op.
    pub fn install_worker_ops(populate_superglobals: bool) {
        #[cfg(php_linked)]
        {
            // SAFETY: WORKER_OPS is a static with a stable address; the C setter
            // copies the struct, so the pointer only needs to be valid for this
            // call. PHP is initialized (worker boot happens after init).
            unsafe { ffi::ephpm_set_worker_ops(&worker_bridge::WORKER_OPS) };
            unsafe {
                ffi::ephpm_worker_set_populate_superglobals(i32::from(populate_superglobals));
            }
            tracing::info!(populate_superglobals, "worker ops wired to PHP native functions");
        }

        #[cfg(not(php_linked))]
        {
            let _ = populate_superglobals;
            tracing::debug!("install_worker_ops no-op (stub mode)");
        }
    }

    /// Register the current OS thread with TSRM for worker-mode execution.
    ///
    /// Worker threads are plain `std::thread`s (not `spawn_blocking`), so they
    /// register once here before booting the framework. Reuses the same
    /// thread-local guard as the fpm path so a thread never double-registers.
    ///
    /// # Errors
    ///
    /// Returns [`PhpError::NotInitialized`] if PHP is not initialized, or
    /// [`PhpError::ThreadInitFailed`] if TSRM registration fails.
    pub fn worker_thread_init() -> Result<(), PhpError> {
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return Err(PhpError::NotInitialized);
        }
        #[cfg(php_linked)]
        {
            Self::ensure_thread_registered()
        }
        #[cfg(not(php_linked))]
        {
            Ok(())
        }
    }

    /// Shut down PHP on the current worker thread: end the long-lived request
    /// and free the TSRM slot + booted framework. Call once, when a worker
    /// thread is exiting (recycle / bailout / drain), so the replacement boots
    /// on a clean context.
    ///
    /// In stub mode this is a no-op.
    pub fn worker_thread_shutdown() {
        #[cfg(php_linked)]
        {
            // Worker-mode crash seam: a fatal kills the worker before its
            // in-flight request ever reaches send_response, so
            // finish_iteration's per-request teardown never ran. Roll back
            // any transaction that request left open (and release staged
            // bridge buffers) here, on the same thread, before the PHP
            // context goes away. (The thread-local session would also drop
            // at thread exit, which closes the connection and abandons the
            // transaction server-side — this makes the rollback explicit
            // and logged instead of incidental.)
            db_bridge::on_request_end();

            // Disarm the TLS guard FIRST so it cannot run a second
            // ephpm_thread_shutdown at thread exit (double ts_free_thread).
            THREAD_REGISTERED.with(|guard| {
                if guard.registered.replace(false) {
                    LIVE_PHP_THREADS.fetch_sub(1, Ordering::AcqRel);
                }
            });
            // SAFETY: called on a TSRM-registered worker thread that is done
            // executing PHP. ephpm_thread_shutdown runs php_request_shutdown +
            // ts_free_thread and frees the thread-local capture buffers.
            unsafe { ffi::ephpm_thread_shutdown() };
            tracing::debug!("worker thread PHP context shut down");
        }
    }

    /// Boot and run a worker on the current (already TSRM-registered) thread.
    ///
    /// Blocks until the framework's `take_request()` loop ends (graceful
    /// shutdown, `worker_max_requests` recycle, a mid-request script exit, or
    /// a fatal bailout) — see [`WorkerExit`] for the outcomes and what the
    /// caller must do for each.
    ///
    /// # Errors
    ///
    /// Returns [`PhpError::NotInitialized`] if PHP is not initialized, or
    /// [`PhpError::ExecutionFailed`] if the script path is invalid.
    #[allow(unused_variables)]
    pub fn run_worker(script: &std::path::Path) -> Result<WorkerExit, PhpError> {
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return Err(PhpError::NotInitialized);
        }

        #[cfg(php_linked)]
        {
            use std::ffi::CString;
            let script_str = script
                .to_str()
                .ok_or_else(|| PhpError::ExecutionFailed("non-UTF8 worker script path".into()))?;
            let c_script = CString::new(script_str)
                .map_err(|e| PhpError::ExecutionFailed(format!("invalid worker script: {e}")))?;
            // SAFETY: this thread is TSRM-registered (worker_thread_init).
            // ephpm_worker_run runs php_execute_script under a SETJMP bailout
            // guard on this thread's own long-lived request context. The
            // CString outlives the call.
            let ret = unsafe { ffi::ephpm_worker_run(c_script.as_ptr()) };
            Ok(match ret {
                0 => WorkerExit::Clean,
                1 => WorkerExit::ScriptExit,
                2 => WorkerExit::ScriptFatal,
                _ => WorkerExit::Fatal,
            })
        }

        #[cfg(not(php_linked))]
        {
            Err(PhpError::ExecutionFailed(
                "PHP not linked — worker mode requires a PHP_SDK_PATH build".into(),
            ))
        }
    }

    /// Set a PHP INI directive for the current request.
    ///
    /// Must be called on a TSRM-registered thread (inside `spawn_blocking`)
    /// before `execute()`. Uses `PHP_INI_SYSTEM` so the value cannot be
    /// overridden by userland `ini_set()`.
    ///
    /// Common use: `open_basedir` and `disable_functions` for vhost isolation.
    #[cfg(php_linked)]
    pub fn set_request_ini(key: &str, value: &str) {
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return;
        }
        // ephpm_request_set_ini reaches zend_string_init -> _emalloc, which
        // requires the per-thread Zend allocator. Without TSRM registration
        // the thread's executor_globals are uninitialised and _emalloc
        // segfaults. Register first so the API is safe to call before
        // execute().
        if Self::ensure_thread_registered().is_err() {
            return;
        }
        let c_key = std::ffi::CString::new(key).expect("INI key contains null byte");
        let c_val = std::ffi::CString::new(value).expect("INI value contains null byte");
        // SAFETY: c_key and c_val are valid null-terminated C strings.
        // ephpm_request_set_ini copies the data via zend_string_init.
        // Under ZTS, this modifies the current thread's INI entries only.
        #[allow(unsafe_code)]
        unsafe {
            ffi::ephpm_request_set_ini(c_key.as_ptr(), c_val.as_ptr());
        }
    }

    /// Stub when PHP is not linked.
    #[cfg(not(php_linked))]
    pub fn set_request_ini(_key: &str, _value: &str) {}

    /// Invalidate every OPcache script whose path starts with `docroot`.
    ///
    /// Returns the number of scripts invalidated on success, or `None` when
    /// OPcache is unavailable (extension missing / disabled), the docroot is
    /// malformed, or a PHP bailout occurred inside the invalidation snippet.
    ///
    /// Called by the ephpm-server per-vhost watcher after it detects that
    /// the cluster-wide `opcache:version:<vhost>` key has advanced. Must be
    /// called on a TSRM-registered thread with an active PHP request
    /// context — safe to call at the start of `execute()` on a
    /// `spawn_blocking` thread.
    ///
    /// In stub mode (no `php_linked`) always returns `None`.
    #[cfg(php_linked)]
    #[must_use]
    pub fn opcache_invalidate_under(docroot: &std::path::Path) -> Option<i64> {
        if !PHP_INITIALIZED.load(Ordering::Acquire) {
            return None;
        }
        // The FFI helper depends on Zend heap-allocated resources; ensure the
        // thread is TSRM-registered before touching them.
        if Self::ensure_thread_registered().is_err() {
            return None;
        }
        let docroot_str = docroot.to_str()?;
        let c_docroot = std::ffi::CString::new(docroot_str).ok()?;
        // SAFETY: c_docroot is a valid null-terminated C string; the FFI
        // helper walks OPcache under a SETJMP bailout guard and does not
        // retain the pointer past the call.
        let count = unsafe { ffi::ephpm_opcache_invalidate_under(c_docroot.as_ptr()) };
        if count < 0 {
            // Failure contract (mirrors the EPHPM_OPCACHE_* #defines in
            // ephpm_wrapper.c). Keep this table and the C-side #defines
            // synchronised:
            //   -1 EPHPM_OPCACHE_UNAVAILABLE — extension missing / disabled
            //                                  or opcache_get_status returned
            //                                  a shape we don't recognise.
            //   -2 EPHPM_OPCACHE_BAILOUT     — SETJMP bailout inside the
            //                                  direct calls.
            //   -3 EPHPM_OPCACHE_EXCEPTION   — a userland exception surfaced;
            //                                  class+message stashed for
            //                                  ephpm_opcache_last_exception().
            let reason = match count {
                -1 => "unavailable",
                -2 => "bailout",
                -3 => "exception",
                _ => "unknown",
            };
            // SAFETY: the pointer is a valid thread-local NUL-terminated
            // buffer owned by the wrapper; we copy it out immediately.
            let exc = unsafe {
                std::ffi::CStr::from_ptr(ffi::ephpm_opcache_last_exception())
                    .to_string_lossy()
                    .into_owned()
            };
            tracing::debug!(
                code = count,
                reason = reason,
                exception = %exc,
                "opcache invalidator failed"
            );
            None
        } else {
            Some(count as i64)
        }
    }

    /// Stub when PHP is not linked.
    #[cfg(not(php_linked))]
    #[must_use]
    pub fn opcache_invalidate_under(_docroot: &std::path::Path) -> Option<i64> {
        None
    }
}

/// The last [`TAIL_BYTES`] of a discarded response body, for the bailout log
/// line.
///
/// The body is thrown away rather than served, so this is the only place PHP's
/// own account of what went wrong (`Fatal error: Allowed memory size ...`,
/// which is emitted into the output stream when `display_errors` is on)
/// survives. The tail, not the head: the fatal is always the last thing
/// written.
#[cfg(php_linked)]
fn truncated_output_tail(body: &[u8]) -> String {
    /// How much of the discarded body to keep in the log line.
    const TAIL_BYTES: usize = 512;
    let tail = &body[body.len().saturating_sub(TAIL_BYTES)..];
    String::from_utf8_lossy(tail).replace(['\n', '\r'], " ")
}

impl Drop for PhpRuntime {
    fn drop(&mut self) {
        if self.initialized {
            tracing::debug!("PhpRuntime dropped");
        }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use serial_test::serial;

    use super::*;

    /// Convenience: build the `Vec<String>` `precscan_cli_ini_flags` expects.
    fn scan(args: &[&str]) -> (Option<String>, bool, Vec<String>) {
        let owned: Vec<String> = args.iter().map(|s| (*s).to_string()).collect();
        precscan_cli_ini_flags(&owned)
    }

    /// Convenience for the `-d` collection assertions.
    fn defines(args: &[&str]) -> Vec<String> {
        scan(args).2
    }

    const NO_DEFINES: Vec<String> = Vec::new();

    #[test]
    fn precscan_no_ini_flags() {
        assert_eq!(scan(&["-r", "echo 1;"]), (None, false, NO_DEFINES));
        assert_eq!(scan(&["script.php", "arg"]), (None, false, NO_DEFINES));
        assert_eq!(scan(&[]), (None, false, NO_DEFINES));
    }

    #[test]
    fn precscan_finds_no_ini() {
        assert_eq!(scan(&["-n", "script.php"]), (None, true, NO_DEFINES));
        // Bundled with another no-arg flag.
        assert_eq!(scan(&["-nl", "script.php"]), (None, true, NO_DEFINES));
    }

    #[test]
    fn precscan_finds_c_separate_and_attached() {
        assert_eq!(scan(&["-c", "/etc/alt.ini", "s.php"]).0.as_deref(), Some("/etc/alt.ini"));
        assert_eq!(scan(&["-c/etc/alt.ini", "s.php"]).0.as_deref(), Some("/etc/alt.ini"));
    }

    #[test]
    fn precscan_n_beats_c() {
        // `-n` wins regardless of `-c` also being present, matching php-cli.
        assert_eq!(scan(&["-c", "/etc/alt.ini", "-n", "s.php"]), (None, true, NO_DEFINES));
    }

    #[test]
    fn precscan_does_not_read_option_arguments() {
        // The `-n`/`-c` inside -r code or -d value must NOT be treated as flags.
        assert_eq!(scan(&["-r", "-n"]), (None, false, NO_DEFINES));
        assert_eq!(scan(&["-r", "echo '-c x';", "arg"]), (None, false, NO_DEFINES));
        let run = scan(&["-d", "auto_prepend_file=-n", "s.php"]);
        assert_eq!((run.0, run.1), (None, false));
        assert_eq!(run.2, vec!["auto_prepend_file=-n".to_string()]);
    }

    #[test]
    fn precscan_stops_at_positional_and_dashes() {
        // A `-n` that appears after the script name is a script argument.
        assert_eq!(scan(&["script.php", "-n"]), (None, false, NO_DEFINES));
        assert_eq!(scan(&["--", "-n"]), (None, false, NO_DEFINES));
        assert_eq!(scan(&["-", "-n"]), (None, false, NO_DEFINES));
        // Same for a `-d`: after the script it belongs to the script.
        assert_eq!(defines(&["script.php", "-d", "foo=1"]), NO_DEFINES);
    }

    #[test]
    fn precscan_composer_invocation() {
        // The canonical composer form: memory_limit collected, no ini flags.
        assert_eq!(
            scan(&["-d", "memory_limit=-1", "composer.phar", "--version"]),
            (None, false, vec!["memory_limit=-1".to_string()])
        );
    }

    #[test]
    fn precscan_skips_long_reflection_arg() {
        // `--rf name` takes a separate arg; a trailing `-n` after it is not
        // reached because the reflection arg is the terminal token here.
        assert_eq!(scan(&["--rf", "strlen"]), (None, false, NO_DEFINES));
        assert_eq!(scan(&["--ini", "-n", "s.php"]), (None, true, NO_DEFINES));
    }

    #[test]
    fn precscan_collects_defines_separate_attached_and_ordered() {
        // Separate and attached forms, order preserved (later `-d` for the
        // same key must stay later — php-cli lets it win at parse time).
        assert_eq!(
            defines(&["-d", "opcache.enable_cli=1", "-dopcache.jit=tracing", "-r", "echo 1;"]),
            vec!["opcache.enable_cli=1".to_string(), "opcache.jit=tracing".to_string()]
        );
        // Bare `-d name` (value defaults to 1 on the C side) and bundling
        // after no-arg flags (`-qd foo`).
        assert_eq!(defines(&["-d", "opcache.enable_cli", "s.php"]), vec!["opcache.enable_cli"]);
        assert_eq!(defines(&["-qd", "foo=bar", "s.php"]), vec!["foo=bar"]);
    }

    #[test]
    fn precscan_defines_survive_no_ini() {
        // `php -n -d x=y` still applies the define, matching php-cli.
        assert_eq!(
            scan(&["-n", "-d", "memory_limit=64M", "s.php"]),
            (None, true, vec!["memory_limit=64M".to_string()])
        );
    }

    fn make_test_request() -> PhpRequest {
        PhpRequest {
            method: "GET".into(),
            uri: "/test.php".into(),
            path: "/test.php".into(),
            query_string: String::new(),
            script_filename: PathBuf::from("/var/www/html/test.php"),
            document_root: PathBuf::from("/var/www/html"),
            headers: Vec::new(),
            body: Vec::new(),
            content_type: None,
            remote_addr: "127.0.0.1:12345".parse().unwrap(),
            server_name: "localhost".into(),
            server_port: 8080,
            is_https: false,
            protocol: "HTTP/1.1".into(),
            env_vars: Vec::new(),
        }
    }

    #[test]
    #[serial]
    fn test_stub_init_succeeds() {
        let _ = PhpRuntime::shutdown();
        assert!(PhpRuntime::init().is_ok());
        let _ = PhpRuntime::shutdown();
    }

    #[test]
    #[serial]
    fn test_stub_init_is_idempotent() {
        let _ = PhpRuntime::shutdown();
        assert!(PhpRuntime::init().is_ok());
        assert!(PhpRuntime::init().is_ok());
        let _ = PhpRuntime::shutdown();
    }

    #[test]
    #[serial]
    fn test_stub_shutdown_after_init() {
        let _ = PhpRuntime::shutdown();
        PhpRuntime::init().unwrap();
        assert!(PhpRuntime::shutdown().is_ok());
    }

    #[test]
    #[serial]
    fn test_stub_shutdown_without_init() {
        let _ = PhpRuntime::shutdown();
        // Shutdown on an already-empty runtime should be a no-op
        assert!(PhpRuntime::shutdown().is_ok());
    }

    #[test]
    #[serial]
    fn test_stub_execute_returns_stub_html() {
        let _ = PhpRuntime::shutdown();
        PhpRuntime::init().unwrap();

        let response = PhpRuntime::execute(make_test_request()).unwrap();
        assert_eq!(response.status, 200);
        assert!(response.headers.iter().any(|(k, v)| k == "Content-Type" && v == "text/html"));
        let body = String::from_utf8(response.body).unwrap();
        assert!(body.contains("ePHPm Stub"));
        assert!(body.contains("test.php"));

        let _ = PhpRuntime::shutdown();
    }

    #[test]
    #[serial]
    fn test_stub_execute_without_init_returns_not_initialized() {
        let _ = PhpRuntime::shutdown();

        let err = PhpRuntime::execute(make_test_request()).unwrap_err();
        assert!(matches!(err, PhpError::NotInitialized), "expected NotInitialized, got {err}");
    }
}
