name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: [self-hosted, linux, x64]
    container: ghcr.io/${{ github.repository }}/ephpm-ci:latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo +nightly fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: [self-hosted, linux, x64]
    container: ghcr.io/${{ github.repository }}/ephpm-ci:latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --all-targets -- -D warnings

  test-linux:
    name: Test (linux-x64)
    runs-on: [self-hosted, linux, x64]
    container: ghcr.io/${{ github.repository }}/ephpm-ci:latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo nextest run --workspace

  test-macos:
    name: Test (macos-arm64)
    runs-on: [self-hosted, macos, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - run: cargo nextest run --workspace

  deny:
    name: Cargo Deny
    runs-on: [self-hosted, linux, x64]
    container: ghcr.io/${{ github.repository }}/ephpm-ci:latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
